//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AgentInstituteFetchRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentInstituteFetchRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://bbps.org/schema}headType"/&gt;
 *         &lt;element name="Search" type="{http://bbps.org/schema}agentSearchType" minOccurs="0"/&gt;
 *         &lt;element name="SearchByTime" type="{http://bbps.org/schema}searchByTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentInstituteFetchRequestType", propOrder = {
    "head",
    "search",
    "searchByTime"
})
@XmlRootElement(name = "AgentInstituteFetchRequest")
public class AgentInstituteFetchRequest
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Search")
    protected AgentSearchType search;
    @XmlElement(name = "SearchByTime")
    protected SearchByTime searchByTime;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link AgentSearchType }
     *     
     */
    public AgentSearchType getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentSearchType }
     *     
     */
    public void setSearch(AgentSearchType value) {
        this.search = value;
    }

    /**
     * Gets the value of the searchByTime property.
     * 
     * @return
     *     possible object is
     *     {@link SearchByTime }
     *     
     */
    public SearchByTime getSearchByTime() {
        return searchByTime;
    }

    /**
     * Sets the value of the searchByTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchByTime }
     *     
     */
    public void setSearchByTime(SearchByTime value) {
        this.searchByTime = value;
    }

}
