//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AlertMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="alertId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creatorId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customParams" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetGroup" type="{http://bbps.org/schema}NotificationTargetGroupTypes"/&gt;
 *         &lt;element name="targetUserIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="targetEmails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="targetMobiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stakeHolder" type="{http://bbps.org/schema}NotificationStakeHolderTypes"/&gt;
 *         &lt;element name="commChannel" type="{http://bbps.org/schema}NotificationCommChannelTypes" minOccurs="0"/&gt;
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="alertType" type="{http://bbps.org/schema}NotificationAlertTypes"/&gt;
 *         &lt;element name="repetInterval" type="{http://bbps.org/schema}NotificationRepetIntervelTypes" minOccurs="0"/&gt;
 *         &lt;element name="repetTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sourceApp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="targetEntity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="additionalEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertMessage", propOrder = {
    "alertId",
    "creatorId",
    "message",
    "name",
    "startDate",
    "endDate",
    "purpose",
    "remarks",
    "customParams",
    "targetGroup",
    "targetUserIds",
    "targetEmails",
    "targetMobiles",
    "stakeHolder",
    "commChannel",
    "active",
    "deleted",
    "alertType",
    "repetInterval",
    "repetTime",
    "sourceApp",
    "targetEntity",
    "additionalEmail"
})
public class AlertMessage
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String alertId;
    @XmlElement(required = true)
    protected String creatorId;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected String name;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(required = true)
    protected String purpose;
    protected String remarks;
    @XmlElement(required = true)
    protected String customParams;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationTargetGroupTypes targetGroup;
    protected String targetUserIds;
    protected String targetEmails;
    protected String targetMobiles;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationStakeHolderTypes stakeHolder;
    @XmlSchemaType(name = "string")
    protected NotificationCommChannelTypes commChannel;
    protected boolean active;
    protected boolean deleted;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationAlertTypes alertType;
    @XmlSchemaType(name = "string")
    protected NotificationRepetIntervelTypes repetInterval;
    protected String repetTime;
    protected String sourceApp;
    protected String targetEntity;
    protected String additionalEmail;

    /**
     * Gets the value of the alertId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertId() {
        return alertId;
    }

    /**
     * Sets the value of the alertId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertId(String value) {
        this.alertId = value;
    }

    /**
     * Gets the value of the creatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * Sets the value of the creatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorId(String value) {
        this.creatorId = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the customParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomParams() {
        return customParams;
    }

    /**
     * Sets the value of the customParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomParams(String value) {
        this.customParams = value;
    }

    /**
     * Gets the value of the targetGroup property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public NotificationTargetGroupTypes getTargetGroup() {
        return targetGroup;
    }

    /**
     * Sets the value of the targetGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public void setTargetGroup(NotificationTargetGroupTypes value) {
        this.targetGroup = value;
    }

    /**
     * Gets the value of the targetUserIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUserIds() {
        return targetUserIds;
    }

    /**
     * Sets the value of the targetUserIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUserIds(String value) {
        this.targetUserIds = value;
    }

    /**
     * Gets the value of the targetEmails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEmails() {
        return targetEmails;
    }

    /**
     * Sets the value of the targetEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEmails(String value) {
        this.targetEmails = value;
    }

    /**
     * Gets the value of the targetMobiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMobiles() {
        return targetMobiles;
    }

    /**
     * Sets the value of the targetMobiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMobiles(String value) {
        this.targetMobiles = value;
    }

    /**
     * Gets the value of the stakeHolder property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public NotificationStakeHolderTypes getStakeHolder() {
        return stakeHolder;
    }

    /**
     * Sets the value of the stakeHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public void setStakeHolder(NotificationStakeHolderTypes value) {
        this.stakeHolder = value;
    }

    /**
     * Gets the value of the commChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCommChannelTypes }
     *     
     */
    public NotificationCommChannelTypes getCommChannel() {
        return commChannel;
    }

    /**
     * Sets the value of the commChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCommChannelTypes }
     *     
     */
    public void setCommChannel(NotificationCommChannelTypes value) {
        this.commChannel = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the alertType property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationAlertTypes }
     *     
     */
    public NotificationAlertTypes getAlertType() {
        return alertType;
    }

    /**
     * Sets the value of the alertType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationAlertTypes }
     *     
     */
    public void setAlertType(NotificationAlertTypes value) {
        this.alertType = value;
    }

    /**
     * Gets the value of the repetInterval property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationRepetIntervelTypes }
     *     
     */
    public NotificationRepetIntervelTypes getRepetInterval() {
        return repetInterval;
    }

    /**
     * Sets the value of the repetInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationRepetIntervelTypes }
     *     
     */
    public void setRepetInterval(NotificationRepetIntervelTypes value) {
        this.repetInterval = value;
    }

    /**
     * Gets the value of the repetTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepetTime() {
        return repetTime;
    }

    /**
     * Sets the value of the repetTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepetTime(String value) {
        this.repetTime = value;
    }

    /**
     * Gets the value of the sourceApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceApp() {
        return sourceApp;
    }

    /**
     * Sets the value of the sourceApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceApp(String value) {
        this.sourceApp = value;
    }

    /**
     * Gets the value of the targetEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntity() {
        return targetEntity;
    }

    /**
     * Sets the value of the targetEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntity(String value) {
        this.targetEntity = value;
    }

    /**
     * Gets the value of the additionalEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalEmail() {
        return additionalEmail;
    }

    /**
     * Sets the value of the additionalEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalEmail(String value) {
        this.additionalEmail = value;
    }

}
