//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amountType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Amt" type="{http://bbps.org/schema}amtType"/&gt;
 *         &lt;element name="AmountBreakUp" type="{http://bbps.org/schema}amtBreakUpType"/&gt;
 *         &lt;element name="SplitPayAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Tag" maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="minAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="maxAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="amountMultiple" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amountType", propOrder = {
    "amt",
    "amountBreakUp",
    "splitPayAmount",
    "tags"
})
public class AmountType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Amt", required = true)
    protected AmtType amt;
    @XmlElement(name = "AmountBreakUp", required = true)
    protected AmtBreakUpType amountBreakUp;
    @XmlElement(name = "SplitPayAmount", required = true)
    protected String splitPayAmount;
    @XmlElement(name = "Tag")
    protected List<AmountType.Tag> tags;

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link AmtType }
     *     
     */
    public AmtType getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmtType }
     *     
     */
    public void setAmt(AmtType value) {
        this.amt = value;
    }

    /**
     * Gets the value of the amountBreakUp property.
     * 
     * @return
     *     possible object is
     *     {@link AmtBreakUpType }
     *     
     */
    public AmtBreakUpType getAmountBreakUp() {
        return amountBreakUp;
    }

    /**
     * Sets the value of the amountBreakUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmtBreakUpType }
     *     
     */
    public void setAmountBreakUp(AmtBreakUpType value) {
        this.amountBreakUp = value;
    }

    /**
     * Gets the value of the splitPayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitPayAmount() {
        return splitPayAmount;
    }

    /**
     * Sets the value of the splitPayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitPayAmount(String value) {
        this.splitPayAmount = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmountType.Tag }
     * 
     * 
     */
    public List<AmountType.Tag> getTags() {
        if (tags == null) {
            tags = new ArrayList<AmountType.Tag>();
        }
        return this.tags;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="minAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="maxAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="amountMultiple" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Tag
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "value", required = true)
        protected String value;
        @XmlAttribute(name = "minAmount")
        protected String minAmount;
        @XmlAttribute(name = "maxAmount")
        protected String maxAmount;
        @XmlAttribute(name = "amountMultiple")
        protected String amountMultiple;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the minAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMinAmount() {
            return minAmount;
        }

        /**
         * Sets the value of the minAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMinAmount(String value) {
            this.minAmount = value;
        }

        /**
         * Gets the value of the maxAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaxAmount() {
            return maxAmount;
        }

        /**
         * Sets the value of the maxAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaxAmount(String value) {
            this.maxAmount = value;
        }

        /**
         * Gets the value of the amountMultiple property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmountMultiple() {
            return amountMultiple;
        }

        /**
         * Sets the value of the amountMultiple property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmountMultiple(String value) {
            this.amountMultiple = value;
        }

    }

}
