//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amtBreakUpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amtBreakUpType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillAmt" type="{http://bbps.org/schema}billAmountType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TDSDeductedAmt" type="{http://bbps.org/schema}TDSDeductedAmountType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amtBreakUpType", propOrder = {
    "billAmts",
    "tdsDeductedAmts"
})
public class AmtBreakUpType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "BillAmt")
    protected List<BillAmountType> billAmts;
    @XmlElement(name = "TDSDeductedAmt")
    protected List<TDSDeductedAmountType> tdsDeductedAmts;

    /**
     * Gets the value of the billAmts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billAmts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillAmts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillAmountType }
     * 
     * 
     */
    public List<BillAmountType> getBillAmts() {
        if (billAmts == null) {
            billAmts = new ArrayList<BillAmountType>();
        }
        return this.billAmts;
    }

    /**
     * Gets the value of the tdsDeductedAmts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tdsDeductedAmts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTDSDeductedAmts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDSDeductedAmountType }
     * 
     * 
     */
    public List<TDSDeductedAmountType> getTDSDeductedAmts() {
        if (tdsDeductedAmts == null) {
            tdsDeductedAmts = new ArrayList<TDSDeductedAmountType>();
        }
        return this.tdsDeductedAmts;
    }

}
