//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amtType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="custConvFee" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="COUcustConvFee" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="billNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amtType")
public class AmtType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "amount")
    protected String amount;
    @XmlAttribute(name = "custConvFee")
    protected String custConvFee;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "COUcustConvFee")
    protected String coUcustConvFee;
    @XmlAttribute(name = "billNumber")
    protected String billNumber;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the custConvFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustConvFee() {
        return custConvFee;
    }

    /**
     * Sets the value of the custConvFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustConvFee(String value) {
        this.custConvFee = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the coUcustConvFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUcustConvFee() {
        return coUcustConvFee;
    }

    /**
     * Sets the value of the coUcustConvFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUcustConvFee(String value) {
        this.coUcustConvFee = value;
    }

    /**
     * Gets the value of the billNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * Sets the value of the billNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNumber(String value) {
        this.billNumber = value;
    }

}
