//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Biller complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Biller"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="billerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerAliasName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerCategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerSubCategoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerResponseType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerAcceptsAdhoc" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="parentBiller" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="parentBillerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerOwnerShp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerCoverage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fetchRequirement" type="{http://bbps.org/schema}FetchRequirement"/&gt;
 *         &lt;element name="authRequirement" type="{http://bbps.org/schema}AuthRequirement"/&gt;
 *         &lt;element name="paymentAmountExactness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="supportBillValidation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerEffctvFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerEffctvTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerTempDeactivationStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerTempDeactivationEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerPaymentModes" type="{http://bbps.org/schema}PaymentModeLimit" maxOccurs="unbounded"/&gt;
 *         &lt;element name="billerPaymentChannels" type="{http://bbps.org/schema}PaymentChannelLimit" maxOccurs="unbounded"/&gt;
 *         &lt;element name="billerCustomerParams" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded"/&gt;
 *         &lt;element name="customerParamGroups" type="{http://bbps.org/schema}CustomerParamGroups" minOccurs="0"/&gt;
 *         &lt;element name="billerSpecificInfos" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="billerResponseParams" type="{http://bbps.org/schema}BillerResponseParams"/&gt;
 *         &lt;element name="billerPlanResponseParams" type="{http://bbps.org/schema}BillerPlanResponseParams"/&gt;
 *         &lt;element name="billerAdditionalInfo" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded"/&gt;
 *         &lt;element name="billerAdditionalInfoPayment" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded"/&gt;
 *         &lt;element name="interchangeFeeConf" type="{http://bbps.org/schema}InterchangeFeeConf" maxOccurs="unbounded"/&gt;
 *         &lt;element name="interchangeFee" type="{http://bbps.org/schema}InterchangeFee" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="supportDeemed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="supportPendingStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="billerTimeOut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="planMdmRequirement" type="{http://bbps.org/schema}PlanMDMRequirement" minOccurs="0"/&gt;
 *         &lt;element name="planAdditionalInfo" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="upmsBillerPaymentModes" type="{http://bbps.org/schema}PaymentModeLimit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="upmsBillerPaymentChannels" type="{http://bbps.org/schema}PaymentChannelLimit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="upmsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="upmsbillerParams" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="upmsBillerType" type="{http://bbps.org/schema}UpmsBillerType"/&gt;
 *         &lt;element name="selectionType" type="{http://bbps.org/schema}SelectionType"/&gt;
 *         &lt;element name="clickpayEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="clickpayValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="additionalFeesEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="additionalFees" type="{http://bbps.org/schema}ParamConfig" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="supportsCalendarDayFetchRetention" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="fetchRetentionInHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deemedSuccessEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="valAddFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="valAddCustParams" type="{http://bbps.org/schema}ValAddCustomerParams" maxOccurs="unbounded"/&gt;
 *         &lt;element name="corporateFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="billAdjustmentFrequency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mandateRequirement" type="{http://bbps.org/schema}MandateRequirement"/&gt;
 *         &lt;element name="blrReqResFormat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pseudoBiller" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="supportCallBack" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ccfResponseRemarks" type="{http://bbps.org/schema}ccfResponseRemarks" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Biller", propOrder = {
    "billerId",
    "billerName",
    "billerAliasName",
    "billerCategoryName",
    "billerSubCategoryName",
    "billerMode",
    "billerResponseType",
    "billerAcceptsAdhoc",
    "parentBiller",
    "parentBillerId",
    "billerOwnerShp",
    "billerCoverage",
    "fetchRequirement",
    "authRequirement",
    "paymentAmountExactness",
    "supportBillValidation",
    "billerEffctvFrom",
    "billerEffctvTo",
    "billerTempDeactivationStart",
    "billerTempDeactivationEnd",
    "billerPaymentModes",
    "billerPaymentChannels",
    "billerCustomerParams",
    "customerParamGroups",
    "billerSpecificInfos",
    "billerResponseParams",
    "billerPlanResponseParams",
    "billerAdditionalInfos",
    "billerAdditionalInfoPayments",
    "interchangeFeeConves",
    "interchangeFees",
    "status",
    "billerDescription",
    "supportDeemed",
    "supportPendingStatus",
    "billerTimeOut",
    "planMdmRequirement",
    "planAdditionalInfos",
    "upmsBillerPaymentModes",
    "upmsBillerPaymentChannels",
    "upmsEnabled",
    "upmsbillerParams",
    "upmsBillerType",
    "selectionType",
    "clickpayEnabled",
    "clickpayValue",
    "additionalFeesEnabled",
    "additionalFees",
    "supportsCalendarDayFetchRetention",
    "fetchRetentionInHours",
    "deemedSuccessEnabled",
    "valAddFlag",
    "valAddCustParams",
    "corporateFlag",
    "billAdjustmentFrequency",
    "mandateRequirement",
    "blrReqResFormat",
    "pseudoBiller",
    "supportCallBack",
    "ccfResponseRemarks"
})
public class Biller
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected String billerId;
    @XmlElement(required = true)
    protected String billerName;
    @XmlElement(required = true)
    protected String billerAliasName;
    @XmlElement(required = true)
    protected String billerCategoryName;
    protected String billerSubCategoryName;
    @XmlElement(required = true)
    protected String billerMode;
    @XmlElement(required = true)
    protected String billerResponseType;
    protected boolean billerAcceptsAdhoc;
    protected boolean parentBiller;
    @XmlElement(required = true)
    protected String parentBillerId;
    @XmlElement(required = true)
    protected String billerOwnerShp;
    @XmlElement(required = true)
    protected String billerCoverage;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FetchRequirement fetchRequirement;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AuthRequirement authRequirement;
    protected String paymentAmountExactness;
    protected String supportBillValidation;
    @XmlElement(required = true)
    protected String billerEffctvFrom;
    @XmlElement(required = true)
    protected String billerEffctvTo;
    protected String billerTempDeactivationStart;
    protected String billerTempDeactivationEnd;
    @XmlElement(required = true)
    protected List<PaymentModeLimit> billerPaymentModes;
    @XmlElement(required = true)
    protected List<PaymentChannelLimit> billerPaymentChannels;
    @XmlElement(required = true)
    protected List<ParamConfig> billerCustomerParams;
    protected CustomerParamGroups customerParamGroups;
    @XmlElement(nillable = true)
    protected List<ParamConfig> billerSpecificInfos;
    @XmlElement(required = true)
    protected BillerResponseParams billerResponseParams;
    @XmlElement(required = true)
    protected BillerPlanResponseParams billerPlanResponseParams;
    @XmlElement(name = "billerAdditionalInfo", required = true)
    protected List<ParamConfig> billerAdditionalInfos;
    @XmlElement(name = "billerAdditionalInfoPayment", required = true)
    protected List<ParamConfig> billerAdditionalInfoPayments;
    @XmlElement(name = "interchangeFeeConf", required = true)
    protected List<InterchangeFeeConf> interchangeFeeConves;
    @XmlElement(name = "interchangeFee", required = true)
    protected List<InterchangeFee> interchangeFees;
    @XmlElement(name = "Status")
    protected String status;
    protected String billerDescription;
    protected String supportDeemed;
    protected String supportPendingStatus;
    protected String billerTimeOut;
    @XmlSchemaType(name = "string")
    protected PlanMDMRequirement planMdmRequirement;
    @XmlElement(name = "planAdditionalInfo")
    protected List<ParamConfig> planAdditionalInfos;
    protected List<PaymentModeLimit> upmsBillerPaymentModes;
    protected List<PaymentChannelLimit> upmsBillerPaymentChannels;
    protected Boolean upmsEnabled;
    protected List<ParamConfig> upmsbillerParams;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected UpmsBillerType upmsBillerType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SelectionType selectionType;
    protected Boolean clickpayEnabled;
    protected String clickpayValue;
    protected Boolean additionalFeesEnabled;
    protected List<ParamConfig> additionalFees;
    protected Boolean supportsCalendarDayFetchRetention;
    protected String fetchRetentionInHours;
    protected Boolean deemedSuccessEnabled;
    protected Boolean valAddFlag;
    @XmlElement(required = true)
    protected List<ValAddCustomerParams> valAddCustParams;
    protected Boolean corporateFlag;
    @XmlElement(required = true)
    protected String billAdjustmentFrequency;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MandateRequirement mandateRequirement;
    @XmlElement(required = true)
    protected String blrReqResFormat;
    protected boolean pseudoBiller;
    protected boolean supportCallBack;
    protected List<CcfResponseRemarks> ccfResponseRemarks;

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the billerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerName() {
        return billerName;
    }

    /**
     * Sets the value of the billerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerName(String value) {
        this.billerName = value;
    }

    /**
     * Gets the value of the billerAliasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerAliasName() {
        return billerAliasName;
    }

    /**
     * Sets the value of the billerAliasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerAliasName(String value) {
        this.billerAliasName = value;
    }

    /**
     * Gets the value of the billerCategoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerCategoryName() {
        return billerCategoryName;
    }

    /**
     * Sets the value of the billerCategoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerCategoryName(String value) {
        this.billerCategoryName = value;
    }

    /**
     * Gets the value of the billerSubCategoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerSubCategoryName() {
        return billerSubCategoryName;
    }

    /**
     * Sets the value of the billerSubCategoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerSubCategoryName(String value) {
        this.billerSubCategoryName = value;
    }

    /**
     * Gets the value of the billerMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerMode() {
        return billerMode;
    }

    /**
     * Sets the value of the billerMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerMode(String value) {
        this.billerMode = value;
    }

    /**
     * Gets the value of the billerResponseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerResponseType() {
        return billerResponseType;
    }

    /**
     * Sets the value of the billerResponseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerResponseType(String value) {
        this.billerResponseType = value;
    }

    /**
     * Gets the value of the billerAcceptsAdhoc property.
     * 
     */
    public boolean isBillerAcceptsAdhoc() {
        return billerAcceptsAdhoc;
    }

    /**
     * Sets the value of the billerAcceptsAdhoc property.
     * 
     */
    public void setBillerAcceptsAdhoc(boolean value) {
        this.billerAcceptsAdhoc = value;
    }

    /**
     * Gets the value of the parentBiller property.
     * 
     */
    public boolean isParentBiller() {
        return parentBiller;
    }

    /**
     * Sets the value of the parentBiller property.
     * 
     */
    public void setParentBiller(boolean value) {
        this.parentBiller = value;
    }

    /**
     * Gets the value of the parentBillerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentBillerId() {
        return parentBillerId;
    }

    /**
     * Sets the value of the parentBillerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentBillerId(String value) {
        this.parentBillerId = value;
    }

    /**
     * Gets the value of the billerOwnerShp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerOwnerShp() {
        return billerOwnerShp;
    }

    /**
     * Sets the value of the billerOwnerShp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerOwnerShp(String value) {
        this.billerOwnerShp = value;
    }

    /**
     * Gets the value of the billerCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerCoverage() {
        return billerCoverage;
    }

    /**
     * Sets the value of the billerCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerCoverage(String value) {
        this.billerCoverage = value;
    }

    /**
     * Gets the value of the fetchRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link FetchRequirement }
     *     
     */
    public FetchRequirement getFetchRequirement() {
        return fetchRequirement;
    }

    /**
     * Sets the value of the fetchRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link FetchRequirement }
     *     
     */
    public void setFetchRequirement(FetchRequirement value) {
        this.fetchRequirement = value;
    }

    /**
     * Gets the value of the authRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link AuthRequirement }
     *     
     */
    public AuthRequirement getAuthRequirement() {
        return authRequirement;
    }

    /**
     * Sets the value of the authRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthRequirement }
     *     
     */
    public void setAuthRequirement(AuthRequirement value) {
        this.authRequirement = value;
    }

    /**
     * Gets the value of the paymentAmountExactness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmountExactness() {
        return paymentAmountExactness;
    }

    /**
     * Sets the value of the paymentAmountExactness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmountExactness(String value) {
        this.paymentAmountExactness = value;
    }

    /**
     * Gets the value of the supportBillValidation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportBillValidation() {
        return supportBillValidation;
    }

    /**
     * Sets the value of the supportBillValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportBillValidation(String value) {
        this.supportBillValidation = value;
    }

    /**
     * Gets the value of the billerEffctvFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerEffctvFrom() {
        return billerEffctvFrom;
    }

    /**
     * Sets the value of the billerEffctvFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerEffctvFrom(String value) {
        this.billerEffctvFrom = value;
    }

    /**
     * Gets the value of the billerEffctvTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerEffctvTo() {
        return billerEffctvTo;
    }

    /**
     * Sets the value of the billerEffctvTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerEffctvTo(String value) {
        this.billerEffctvTo = value;
    }

    /**
     * Gets the value of the billerTempDeactivationStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerTempDeactivationStart() {
        return billerTempDeactivationStart;
    }

    /**
     * Sets the value of the billerTempDeactivationStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerTempDeactivationStart(String value) {
        this.billerTempDeactivationStart = value;
    }

    /**
     * Gets the value of the billerTempDeactivationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerTempDeactivationEnd() {
        return billerTempDeactivationEnd;
    }

    /**
     * Sets the value of the billerTempDeactivationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerTempDeactivationEnd(String value) {
        this.billerTempDeactivationEnd = value;
    }

    /**
     * Gets the value of the billerPaymentModes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerPaymentModes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerPaymentModes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentModeLimit }
     * 
     * 
     */
    public List<PaymentModeLimit> getBillerPaymentModes() {
        if (billerPaymentModes == null) {
            billerPaymentModes = new ArrayList<PaymentModeLimit>();
        }
        return this.billerPaymentModes;
    }

    /**
     * Gets the value of the billerPaymentChannels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerPaymentChannels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerPaymentChannels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentChannelLimit }
     * 
     * 
     */
    public List<PaymentChannelLimit> getBillerPaymentChannels() {
        if (billerPaymentChannels == null) {
            billerPaymentChannels = new ArrayList<PaymentChannelLimit>();
        }
        return this.billerPaymentChannels;
    }

    /**
     * Gets the value of the billerCustomerParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerCustomerParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerCustomerParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getBillerCustomerParams() {
        if (billerCustomerParams == null) {
            billerCustomerParams = new ArrayList<ParamConfig>();
        }
        return this.billerCustomerParams;
    }

    /**
     * Gets the value of the customerParamGroups property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerParamGroups }
     *     
     */
    public CustomerParamGroups getCustomerParamGroups() {
        return customerParamGroups;
    }

    /**
     * Sets the value of the customerParamGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerParamGroups }
     *     
     */
    public void setCustomerParamGroups(CustomerParamGroups value) {
        this.customerParamGroups = value;
    }

    /**
     * Gets the value of the billerSpecificInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerSpecificInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerSpecificInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getBillerSpecificInfos() {
        if (billerSpecificInfos == null) {
            billerSpecificInfos = new ArrayList<ParamConfig>();
        }
        return this.billerSpecificInfos;
    }

    /**
     * Gets the value of the billerResponseParams property.
     * 
     * @return
     *     possible object is
     *     {@link BillerResponseParams }
     *     
     */
    public BillerResponseParams getBillerResponseParams() {
        return billerResponseParams;
    }

    /**
     * Sets the value of the billerResponseParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerResponseParams }
     *     
     */
    public void setBillerResponseParams(BillerResponseParams value) {
        this.billerResponseParams = value;
    }

    /**
     * Gets the value of the billerPlanResponseParams property.
     * 
     * @return
     *     possible object is
     *     {@link BillerPlanResponseParams }
     *     
     */
    public BillerPlanResponseParams getBillerPlanResponseParams() {
        return billerPlanResponseParams;
    }

    /**
     * Sets the value of the billerPlanResponseParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerPlanResponseParams }
     *     
     */
    public void setBillerPlanResponseParams(BillerPlanResponseParams value) {
        this.billerPlanResponseParams = value;
    }

    /**
     * Gets the value of the billerAdditionalInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerAdditionalInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerAdditionalInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getBillerAdditionalInfos() {
        if (billerAdditionalInfos == null) {
            billerAdditionalInfos = new ArrayList<ParamConfig>();
        }
        return this.billerAdditionalInfos;
    }

    /**
     * Gets the value of the billerAdditionalInfoPayments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerAdditionalInfoPayments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerAdditionalInfoPayments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getBillerAdditionalInfoPayments() {
        if (billerAdditionalInfoPayments == null) {
            billerAdditionalInfoPayments = new ArrayList<ParamConfig>();
        }
        return this.billerAdditionalInfoPayments;
    }

    /**
     * Gets the value of the interchangeFeeConves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interchangeFeeConves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterchangeFeeConves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterchangeFeeConf }
     * 
     * 
     */
    public List<InterchangeFeeConf> getInterchangeFeeConves() {
        if (interchangeFeeConves == null) {
            interchangeFeeConves = new ArrayList<InterchangeFeeConf>();
        }
        return this.interchangeFeeConves;
    }

    /**
     * Gets the value of the interchangeFees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interchangeFees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterchangeFees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterchangeFee }
     * 
     * 
     */
    public List<InterchangeFee> getInterchangeFees() {
        if (interchangeFees == null) {
            interchangeFees = new ArrayList<InterchangeFee>();
        }
        return this.interchangeFees;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the billerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerDescription() {
        return billerDescription;
    }

    /**
     * Sets the value of the billerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerDescription(String value) {
        this.billerDescription = value;
    }

    /**
     * Gets the value of the supportDeemed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportDeemed() {
        return supportDeemed;
    }

    /**
     * Sets the value of the supportDeemed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportDeemed(String value) {
        this.supportDeemed = value;
    }

    /**
     * Gets the value of the supportPendingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportPendingStatus() {
        return supportPendingStatus;
    }

    /**
     * Sets the value of the supportPendingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportPendingStatus(String value) {
        this.supportPendingStatus = value;
    }

    /**
     * Gets the value of the billerTimeOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerTimeOut() {
        return billerTimeOut;
    }

    /**
     * Sets the value of the billerTimeOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerTimeOut(String value) {
        this.billerTimeOut = value;
    }

    /**
     * Gets the value of the planMdmRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link PlanMDMRequirement }
     *     
     */
    public PlanMDMRequirement getPlanMdmRequirement() {
        return planMdmRequirement;
    }

    /**
     * Sets the value of the planMdmRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanMDMRequirement }
     *     
     */
    public void setPlanMdmRequirement(PlanMDMRequirement value) {
        this.planMdmRequirement = value;
    }

    /**
     * Gets the value of the planAdditionalInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planAdditionalInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanAdditionalInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getPlanAdditionalInfos() {
        if (planAdditionalInfos == null) {
            planAdditionalInfos = new ArrayList<ParamConfig>();
        }
        return this.planAdditionalInfos;
    }

    /**
     * Gets the value of the upmsBillerPaymentModes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upmsBillerPaymentModes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpmsBillerPaymentModes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentModeLimit }
     * 
     * 
     */
    public List<PaymentModeLimit> getUpmsBillerPaymentModes() {
        if (upmsBillerPaymentModes == null) {
            upmsBillerPaymentModes = new ArrayList<PaymentModeLimit>();
        }
        return this.upmsBillerPaymentModes;
    }

    /**
     * Gets the value of the upmsBillerPaymentChannels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upmsBillerPaymentChannels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpmsBillerPaymentChannels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentChannelLimit }
     * 
     * 
     */
    public List<PaymentChannelLimit> getUpmsBillerPaymentChannels() {
        if (upmsBillerPaymentChannels == null) {
            upmsBillerPaymentChannels = new ArrayList<PaymentChannelLimit>();
        }
        return this.upmsBillerPaymentChannels;
    }

    /**
     * Gets the value of the upmsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpmsEnabled() {
        return upmsEnabled;
    }

    /**
     * Sets the value of the upmsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpmsEnabled(Boolean value) {
        this.upmsEnabled = value;
    }

    /**
     * Gets the value of the upmsbillerParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upmsbillerParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpmsbillerParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getUpmsbillerParams() {
        if (upmsbillerParams == null) {
            upmsbillerParams = new ArrayList<ParamConfig>();
        }
        return this.upmsbillerParams;
    }

    /**
     * Gets the value of the upmsBillerType property.
     * 
     * @return
     *     possible object is
     *     {@link UpmsBillerType }
     *     
     */
    public UpmsBillerType getUpmsBillerType() {
        return upmsBillerType;
    }

    /**
     * Sets the value of the upmsBillerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpmsBillerType }
     *     
     */
    public void setUpmsBillerType(UpmsBillerType value) {
        this.upmsBillerType = value;
    }

    /**
     * Gets the value of the selectionType property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionType }
     *     
     */
    public SelectionType getSelectionType() {
        return selectionType;
    }

    /**
     * Sets the value of the selectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionType }
     *     
     */
    public void setSelectionType(SelectionType value) {
        this.selectionType = value;
    }

    /**
     * Gets the value of the clickpayEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClickpayEnabled() {
        return clickpayEnabled;
    }

    /**
     * Sets the value of the clickpayEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClickpayEnabled(Boolean value) {
        this.clickpayEnabled = value;
    }

    /**
     * Gets the value of the clickpayValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClickpayValue() {
        return clickpayValue;
    }

    /**
     * Sets the value of the clickpayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClickpayValue(String value) {
        this.clickpayValue = value;
    }

    /**
     * Gets the value of the additionalFeesEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdditionalFeesEnabled() {
        return additionalFeesEnabled;
    }

    /**
     * Sets the value of the additionalFeesEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdditionalFeesEnabled(Boolean value) {
        this.additionalFeesEnabled = value;
    }

    /**
     * Gets the value of the additionalFees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalFees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalFees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamConfig }
     * 
     * 
     */
    public List<ParamConfig> getAdditionalFees() {
        if (additionalFees == null) {
            additionalFees = new ArrayList<ParamConfig>();
        }
        return this.additionalFees;
    }

    /**
     * Gets the value of the supportsCalendarDayFetchRetention property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportsCalendarDayFetchRetention() {
        return supportsCalendarDayFetchRetention;
    }

    /**
     * Sets the value of the supportsCalendarDayFetchRetention property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsCalendarDayFetchRetention(Boolean value) {
        this.supportsCalendarDayFetchRetention = value;
    }

    /**
     * Gets the value of the fetchRetentionInHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetchRetentionInHours() {
        return fetchRetentionInHours;
    }

    /**
     * Sets the value of the fetchRetentionInHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetchRetentionInHours(String value) {
        this.fetchRetentionInHours = value;
    }

    /**
     * Gets the value of the deemedSuccessEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeemedSuccessEnabled() {
        return deemedSuccessEnabled;
    }

    /**
     * Sets the value of the deemedSuccessEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeemedSuccessEnabled(Boolean value) {
        this.deemedSuccessEnabled = value;
    }

    /**
     * Gets the value of the valAddFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValAddFlag() {
        return valAddFlag;
    }

    /**
     * Sets the value of the valAddFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValAddFlag(Boolean value) {
        this.valAddFlag = value;
    }

    /**
     * Gets the value of the valAddCustParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valAddCustParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValAddCustParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValAddCustomerParams }
     * 
     * 
     */
    public List<ValAddCustomerParams> getValAddCustParams() {
        if (valAddCustParams == null) {
            valAddCustParams = new ArrayList<ValAddCustomerParams>();
        }
        return this.valAddCustParams;
    }

    /**
     * Gets the value of the corporateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCorporateFlag() {
        return corporateFlag;
    }

    /**
     * Sets the value of the corporateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCorporateFlag(Boolean value) {
        this.corporateFlag = value;
    }

    /**
     * Gets the value of the billAdjustmentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillAdjustmentFrequency() {
        return billAdjustmentFrequency;
    }

    /**
     * Sets the value of the billAdjustmentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillAdjustmentFrequency(String value) {
        this.billAdjustmentFrequency = value;
    }

    /**
     * Gets the value of the mandateRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link MandateRequirement }
     *     
     */
    public MandateRequirement getMandateRequirement() {
        return mandateRequirement;
    }

    /**
     * Sets the value of the mandateRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateRequirement }
     *     
     */
    public void setMandateRequirement(MandateRequirement value) {
        this.mandateRequirement = value;
    }

    /**
     * Gets the value of the blrReqResFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlrReqResFormat() {
        return blrReqResFormat;
    }

    /**
     * Sets the value of the blrReqResFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlrReqResFormat(String value) {
        this.blrReqResFormat = value;
    }

    /**
     * Gets the value of the pseudoBiller property.
     * 
     */
    public boolean isPseudoBiller() {
        return pseudoBiller;
    }

    /**
     * Sets the value of the pseudoBiller property.
     * 
     */
    public void setPseudoBiller(boolean value) {
        this.pseudoBiller = value;
    }

    /**
     * Gets the value of the supportCallBack property.
     * 
     */
    public boolean isSupportCallBack() {
        return supportCallBack;
    }

    /**
     * Sets the value of the supportCallBack property.
     * 
     */
    public void setSupportCallBack(boolean value) {
        this.supportCallBack = value;
    }

    /**
     * Gets the value of the ccfResponseRemarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccfResponseRemarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCcfResponseRemarks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CcfResponseRemarks }
     * 
     * 
     */
    public List<CcfResponseRemarks> getCcfResponseRemarks() {
        if (ccfResponseRemarks == null) {
            ccfResponseRemarks = new ArrayList<CcfResponseRemarks>();
        }
        return this.ccfResponseRemarks;
    }

}
