//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillValidationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillValidationRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://bbps.org/schema}headType"/&gt;
 *         &lt;element name="Agent" type="{http://bbps.org/schema}agentType"/&gt;
 *         &lt;element name="BillDetails" type="{http://bbps.org/schema}billDetailsType"/&gt;
 *         &lt;element name="Amount" type="{http://bbps.org/schema}amt" minOccurs="0"/&gt;
 *         &lt;element name="Upms" type="{http://bbps.org/schema}upmsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillValidationRequestType", propOrder = {
    "head",
    "agent",
    "billDetails",
    "amount",
    "upms"
})
@XmlRootElement(name = "BillValidationRequest")
public class BillValidationRequest
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Agent", required = true)
    protected AgentType agent;
    @XmlElement(name = "BillDetails", required = true)
    protected BillDetailsType billDetails;
    @XmlElement(name = "Amount")
    protected Amt amount;
    @XmlElement(name = "Upms")
    protected UpmsType upms;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link AgentType }
     *     
     */
    public AgentType getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentType }
     *     
     */
    public void setAgent(AgentType value) {
        this.agent = value;
    }

    /**
     * Gets the value of the billDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BillDetailsType }
     *     
     */
    public BillDetailsType getBillDetails() {
        return billDetails;
    }

    /**
     * Sets the value of the billDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillDetailsType }
     *     
     */
    public void setBillDetails(BillDetailsType value) {
        this.billDetails = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Amt }
     *     
     */
    public Amt getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amt }
     *     
     */
    public void setAmount(Amt value) {
        this.amount = value;
    }

    /**
     * Gets the value of the upms property.
     * 
     * @return
     *     possible object is
     *     {@link UpmsType }
     *     
     */
    public UpmsType getUpms() {
        return upms;
    }

    /**
     * Sets the value of the upms property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpmsType }
     *     
     */
    public void setUpms(UpmsType value) {
        this.upms = value;
    }

}
