//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentResponseTypeLite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentResponseTypeLite"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="billerId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="approvalRefNum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="responseCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="responseReason" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txnReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="directBillContentId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="paymentRefId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentResponseTypeLite")
@XmlRootElement(name = "BillPaymentResponseLite")
public class BillPaymentResponseLite
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "billerId", required = true)
    protected String billerId;
    @XmlAttribute(name = "ts", required = true)
    protected String ts;
    @XmlAttribute(name = "refId", required = true)
    protected String refId;
    @XmlAttribute(name = "approvalRefNum", required = true)
    protected String approvalRefNum;
    @XmlAttribute(name = "responseCode", required = true)
    protected String responseCode;
    @XmlAttribute(name = "responseReason", required = true)
    protected String responseReason;
    @XmlAttribute(name = "txnReferenceId")
    protected String txnReferenceId;
    @XmlAttribute(name = "directBillContentId")
    protected String directBillContentId;
    @XmlAttribute(name = "paymentRefId")
    protected String paymentRefId;

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the approvalRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalRefNum() {
        return approvalRefNum;
    }

    /**
     * Sets the value of the approvalRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalRefNum(String value) {
        this.approvalRefNum = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseReason() {
        return responseReason;
    }

    /**
     * Sets the value of the responseReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseReason(String value) {
        this.responseReason = value;
    }

    /**
     * Gets the value of the txnReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnReferenceId() {
        return txnReferenceId;
    }

    /**
     * Sets the value of the txnReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnReferenceId(String value) {
        this.txnReferenceId = value;
    }

    /**
     * Gets the value of the directBillContentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectBillContentId() {
        return directBillContentId;
    }

    /**
     * Sets the value of the directBillContentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectBillContentId(String value) {
        this.directBillContentId = value;
    }

    /**
     * Gets the value of the paymentRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRefId() {
        return paymentRefId;
    }

    /**
     * Sets the value of the paymentRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRefId(String value) {
        this.paymentRefId = value;
    }

}
