//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillerFetchRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillerFetchRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://bbps.org/schema}headType"/&gt;
 *         &lt;element name="SearchMyBiller" type="{http://bbps.org/schema}searchMyBiller" minOccurs="0"/&gt;
 *         &lt;element name="Search" type="{http://bbps.org/schema}searchType" minOccurs="0"/&gt;
 *         &lt;element name="SearchByTime" type="{http://bbps.org/schema}searchByTime" minOccurs="0"/&gt;
 *         &lt;element name="SearchByFeature" type="{http://bbps.org/schema}searchByFeature" minOccurs="0"/&gt;
 *         &lt;element name="Paging" type="{http://bbps.org/schema}paging" minOccurs="0"/&gt;
 *         &lt;element name="afterbillerid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="beforebillerid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillerFetchRequestType", propOrder = {
    "head",
    "searchMyBiller",
    "search",
    "searchByTime",
    "searchByFeature",
    "paging",
    "afterbillerid",
    "beforebillerid",
    "limit"
})
@XmlRootElement(name = "BillerFetchRequest")
public class BillerFetchRequest
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "SearchMyBiller")
    protected SearchMyBiller searchMyBiller;
    @XmlElement(name = "Search")
    protected SearchType search;
    @XmlElement(name = "SearchByTime")
    protected SearchByTime searchByTime;
    @XmlElement(name = "SearchByFeature")
    @XmlSchemaType(name = "string")
    protected SearchByFeature searchByFeature;
    @XmlElement(name = "Paging")
    protected Paging paging;
    protected String afterbillerid;
    protected String beforebillerid;
    protected BigInteger limit;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the searchMyBiller property.
     * 
     * @return
     *     possible object is
     *     {@link SearchMyBiller }
     *     
     */
    public SearchMyBiller getSearchMyBiller() {
        return searchMyBiller;
    }

    /**
     * Sets the value of the searchMyBiller property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchMyBiller }
     *     
     */
    public void setSearchMyBiller(SearchMyBiller value) {
        this.searchMyBiller = value;
    }

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link SearchType }
     *     
     */
    public SearchType getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchType }
     *     
     */
    public void setSearch(SearchType value) {
        this.search = value;
    }

    /**
     * Gets the value of the searchByTime property.
     * 
     * @return
     *     possible object is
     *     {@link SearchByTime }
     *     
     */
    public SearchByTime getSearchByTime() {
        return searchByTime;
    }

    /**
     * Sets the value of the searchByTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchByTime }
     *     
     */
    public void setSearchByTime(SearchByTime value) {
        this.searchByTime = value;
    }

    /**
     * Gets the value of the searchByFeature property.
     * 
     * @return
     *     possible object is
     *     {@link SearchByFeature }
     *     
     */
    public SearchByFeature getSearchByFeature() {
        return searchByFeature;
    }

    /**
     * Sets the value of the searchByFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchByFeature }
     *     
     */
    public void setSearchByFeature(SearchByFeature value) {
        this.searchByFeature = value;
    }

    /**
     * Gets the value of the paging property.
     * 
     * @return
     *     possible object is
     *     {@link Paging }
     *     
     */
    public Paging getPaging() {
        return paging;
    }

    /**
     * Sets the value of the paging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paging }
     *     
     */
    public void setPaging(Paging value) {
        this.paging = value;
    }

    /**
     * Gets the value of the afterbillerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterbillerid() {
        return afterbillerid;
    }

    /**
     * Sets the value of the afterbillerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterbillerid(String value) {
        this.afterbillerid = value;
    }

    /**
     * Gets the value of the beforebillerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforebillerid() {
        return beforebillerid;
    }

    /**
     * Sets the value of the beforebillerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforebillerid(String value) {
        this.beforebillerid = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLimit(BigInteger value) {
        this.limit = value;
    }

}
