//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BulkAckType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BulkAckType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OuId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Api" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ts" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RspCd" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Acks" type="{http://bbps.org/schema}Ack" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BulkAckType", propOrder = {
    "parentRefId",
    "ouId",
    "api",
    "ts",
    "rspCd",
    "acks"
})
@XmlRootElement(name = "BulkAck")
public class BulkAck
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "ParentRefId", required = true)
    protected String parentRefId;
    @XmlElement(name = "OuId")
    protected String ouId;
    @XmlElement(name = "Api")
    protected String api;
    @XmlElement(name = "Ts", required = true)
    protected String ts;
    @XmlElement(name = "RspCd", required = true)
    protected String rspCd;
    @XmlElement(name = "Acks", required = true)
    protected List<Ack> acks;

    /**
     * Gets the value of the parentRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentRefId() {
        return parentRefId;
    }

    /**
     * Sets the value of the parentRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentRefId(String value) {
        this.parentRefId = value;
    }

    /**
     * Gets the value of the ouId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOuId() {
        return ouId;
    }

    /**
     * Sets the value of the ouId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOuId(String value) {
        this.ouId = value;
    }

    /**
     * Gets the value of the api property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApi() {
        return api;
    }

    /**
     * Sets the value of the api property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApi(String value) {
        this.api = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the rspCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRspCd() {
        return rspCd;
    }

    /**
     * Sets the value of the rspCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRspCd(String value) {
        this.rspCd = value;
    }

    /**
     * Gets the value of the acks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ack }
     * 
     * 
     */
    public List<Ack> getAcks() {
        if (acks == null) {
            acks = new ArrayList<Ack>();
        }
        return this.acks;
    }

}
