//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditAdjustments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditAdjustments"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="caId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="caInitiatedDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="caStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="caClosureDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refundedTxnAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refundedPenaltyAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditAdjustments")
public class CreditAdjustments
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "caId")
    protected String caId;
    @XmlAttribute(name = "caInitiatedDate")
    protected String caInitiatedDate;
    @XmlAttribute(name = "caStatus")
    protected String caStatus;
    @XmlAttribute(name = "caClosureDate")
    protected String caClosureDate;
    @XmlAttribute(name = "refundedTxnAmount")
    protected String refundedTxnAmount;
    @XmlAttribute(name = "refundedPenaltyAmount")
    protected String refundedPenaltyAmount;

    /**
     * Gets the value of the caId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaId() {
        return caId;
    }

    /**
     * Sets the value of the caId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaId(String value) {
        this.caId = value;
    }

    /**
     * Gets the value of the caInitiatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaInitiatedDate() {
        return caInitiatedDate;
    }

    /**
     * Sets the value of the caInitiatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaInitiatedDate(String value) {
        this.caInitiatedDate = value;
    }

    /**
     * Gets the value of the caStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaStatus() {
        return caStatus;
    }

    /**
     * Sets the value of the caStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaStatus(String value) {
        this.caStatus = value;
    }

    /**
     * Gets the value of the caClosureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaClosureDate() {
        return caClosureDate;
    }

    /**
     * Sets the value of the caClosureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaClosureDate(String value) {
        this.caClosureDate = value;
    }

    /**
     * Gets the value of the refundedTxnAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundedTxnAmount() {
        return refundedTxnAmount;
    }

    /**
     * Sets the value of the refundedTxnAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundedTxnAmount(String value) {
        this.refundedTxnAmount = value;
    }

    /**
     * Gets the value of the refundedPenaltyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundedPenaltyAmount() {
        return refundedPenaltyAmount;
    }

    /**
     * Sets the value of the refundedPenaltyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundedPenaltyAmount(String value) {
        this.refundedPenaltyAmount = value;
    }

}
