//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for custIdentityConstant.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="custIdentityConstant"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EMAIL"/&gt;
 *     &lt;enumeration value="PAN"/&gt;
 *     &lt;enumeration value="AADHAAR"/&gt;
 *     &lt;enumeration value="AUTHMETHOD"/&gt;
 *     &lt;enumeration value="LOAN_ACCOUNT"/&gt;
 *     &lt;enumeration value="CAN"/&gt;
 *     &lt;enumeration value="MOBILE"/&gt;
 *     &lt;enumeration value="ACCOUNT_HOLDER_NAME"/&gt;
 *     &lt;enumeration value="ACCOUNT_TYPE"/&gt;
 *     &lt;enumeration value="REMITTER_NAME"/&gt;
 *     &lt;enumeration value="ADDRESS"/&gt;
 *     &lt;enumeration value="DATEANDPLACEOFBIRTH"/&gt;
 *     &lt;enumeration value="NATIONALIDENTITYNUMBER"/&gt;
 *     &lt;enumeration value="CUSTOMERIDENTIFICATIONNUMBER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "custIdentityConstant")
@XmlEnum
public enum CustIdentityConstant {

    EMAIL,
    PAN,
    AADHAAR,
    AUTHMETHOD,
    LOAN_ACCOUNT,
    CAN,
    MOBILE,
    ACCOUNT_HOLDER_NAME,
    ACCOUNT_TYPE,
    REMITTER_NAME,
    ADDRESS,
    DATEANDPLACEOFBIRTH,
    NATIONALIDENTITYNUMBER,
    CUSTOMERIDENTIFICATIONNUMBER;

    public String value() {
        return name();
    }

    public static CustIdentityConstant fromValue(String v) {
        return valueOf(v);
    }

}
