//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for directBillChannelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="directBillChannelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="L1QR"/&gt;
 *     &lt;enumeration value="L2QR"/&gt;
 *     &lt;enumeration value="L3QR"/&gt;
 *     &lt;enumeration value="L1PL"/&gt;
 *     &lt;enumeration value="L2PL"/&gt;
 *     &lt;enumeration value="L3PL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "directBillChannelType")
@XmlEnum
public enum DirectBillChannelType {

    @XmlEnumValue("L1QR")
    L_1_QR("L1QR"),
    @XmlEnumValue("L2QR")
    L_2_QR("L2QR"),
    @XmlEnumValue("L3QR")
    L_3_QR("L3QR"),
    @XmlEnumValue("L1PL")
    L_1_PL("L1PL"),
    @XmlEnumValue("L2PL")
    L_2_PL("L2PL"),
    @XmlEnumValue("L3PL")
    L_3_PL("L3PL");
    private final String value;

    DirectBillChannelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DirectBillChannelType fromValue(String v) {
        for (DirectBillChannelType c: DirectBillChannelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
