//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenerateBillRefNumberRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenerateBillRefNumberRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://bbps.org/schema}headType"/&gt;
 *         &lt;element name="Analytics" type="{http://bbps.org/schema}analyticsType" minOccurs="0"/&gt;
 *         &lt;element name="Txn" type="{http://bbps.org/schema}txnType"/&gt;
 *         &lt;element name="Customer" type="{http://bbps.org/schema}customerDtlsType"/&gt;
 *         &lt;element name="Agent" type="{http://bbps.org/schema}agentType"/&gt;
 *         &lt;element name="BillDetails" type="{http://bbps.org/schema}billDetailsType"/&gt;
 *         &lt;element name="PlanDetails" type="{http://bbps.org/schema}planDetailsType" minOccurs="0"/&gt;
 *         &lt;element name="BillerResponse" type="{http://bbps.org/schema}billerResponseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInfo" type="{http://bbps.org/schema}additionalInfoType" minOccurs="0"/&gt;
 *         &lt;element name="PaymentMethod" type="{http://bbps.org/schema}pmtMtdType"/&gt;
 *         &lt;element name="Amount" type="{http://bbps.org/schema}amountType"/&gt;
 *         &lt;element name="PaymentInformation" type="{http://bbps.org/schema}pymntInfType"/&gt;
 *         &lt;element name="Upms" type="{http://bbps.org/schema}upmsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerateBillRefNumberRequestType", propOrder = {
    "head",
    "analytics",
    "txn",
    "customer",
    "agent",
    "billDetails",
    "planDetails",
    "billerResponses",
    "additionalInfo",
    "paymentMethod",
    "amount",
    "paymentInformation",
    "upms"
})
@XmlRootElement(name = "GenerateBillRefNumberRequest")
public class GenerateBillRefNumberRequest
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Analytics")
    protected AnalyticsType analytics;
    @XmlElement(name = "Txn", required = true)
    protected TxnType txn;
    @XmlElement(name = "Customer", required = true)
    protected CustomerDtlsType customer;
    @XmlElement(name = "Agent", required = true)
    protected AgentType agent;
    @XmlElement(name = "BillDetails", required = true)
    protected BillDetailsType billDetails;
    @XmlElement(name = "PlanDetails")
    protected PlanDetailsType planDetails;
    @XmlElement(name = "BillerResponse")
    protected List<BillerResponseType> billerResponses;
    @XmlElement(name = "AdditionalInfo")
    protected AdditionalInfoType additionalInfo;
    @XmlElement(name = "PaymentMethod", required = true)
    protected PmtMtdType paymentMethod;
    @XmlElement(name = "Amount", required = true)
    protected AmountType amount;
    @XmlElement(name = "PaymentInformation", required = true)
    protected PymntInfType paymentInformation;
    @XmlElement(name = "Upms")
    protected UpmsType upms;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the analytics property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyticsType }
     *     
     */
    public AnalyticsType getAnalytics() {
        return analytics;
    }

    /**
     * Sets the value of the analytics property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyticsType }
     *     
     */
    public void setAnalytics(AnalyticsType value) {
        this.analytics = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link TxnType }
     *     
     */
    public TxnType getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnType }
     *     
     */
    public void setTxn(TxnType value) {
        this.txn = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDtlsType }
     *     
     */
    public CustomerDtlsType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDtlsType }
     *     
     */
    public void setCustomer(CustomerDtlsType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link AgentType }
     *     
     */
    public AgentType getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentType }
     *     
     */
    public void setAgent(AgentType value) {
        this.agent = value;
    }

    /**
     * Gets the value of the billDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BillDetailsType }
     *     
     */
    public BillDetailsType getBillDetails() {
        return billDetails;
    }

    /**
     * Sets the value of the billDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillDetailsType }
     *     
     */
    public void setBillDetails(BillDetailsType value) {
        this.billDetails = value;
    }

    /**
     * Gets the value of the planDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDetailsType }
     *     
     */
    public PlanDetailsType getPlanDetails() {
        return planDetails;
    }

    /**
     * Sets the value of the planDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDetailsType }
     *     
     */
    public void setPlanDetails(PlanDetailsType value) {
        this.planDetails = value;
    }

    /**
     * Gets the value of the billerResponses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerResponses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerResponses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillerResponseType }
     * 
     * 
     */
    public List<BillerResponseType> getBillerResponses() {
        if (billerResponses == null) {
            billerResponses = new ArrayList<BillerResponseType>();
        }
        return this.billerResponses;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoType }
     *     
     */
    public AdditionalInfoType getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoType }
     *     
     */
    public void setAdditionalInfo(AdditionalInfoType value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PmtMtdType }
     *     
     */
    public PmtMtdType getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtMtdType }
     *     
     */
    public void setPaymentMethod(PmtMtdType value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the paymentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PymntInfType }
     *     
     */
    public PymntInfType getPaymentInformation() {
        return paymentInformation;
    }

    /**
     * Sets the value of the paymentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PymntInfType }
     *     
     */
    public void setPaymentInformation(PymntInfType value) {
        this.paymentInformation = value;
    }

    /**
     * Gets the value of the upms property.
     * 
     * @return
     *     possible object is
     *     {@link UpmsType }
     *     
     */
    public UpmsType getUpms() {
        return upms;
    }

    /**
     * Sets the value of the upms property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpmsType }
     *     
     */
    public void setUpms(UpmsType value) {
        this.upms = value;
    }

}
