//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterchangeFeeDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="InterchangeFeeDirection"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="B2C"/&gt;
 *     &lt;enumeration value="C2B"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "InterchangeFeeDirection")
@XmlEnum
public enum InterchangeFeeDirection {

    @XmlEnumValue("B2C")
    B_2_C("B2C"),
    @XmlEnumValue("C2B")
    C_2_B("C2B");
    private final String value;

    InterchangeFeeDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterchangeFeeDirection fromValue(String v) {
        for (InterchangeFeeDirection c: InterchangeFeeDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
