//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterchangeFeeDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterchangeFeeDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tranAmtRangeMax" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="tranAmtRangeMin" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="percentFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="flatFee" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="effctvFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="effctvTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterchangeFeeDetailsType", propOrder = {
    "tranAmtRangeMax",
    "tranAmtRangeMin",
    "percentFee",
    "flatFee",
    "effctvFrom",
    "effctvTo"
})
public class InterchangeFeeDetailsType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected long tranAmtRangeMax;
    protected long tranAmtRangeMin;
    @XmlElement(required = true)
    protected BigDecimal percentFee;
    @XmlElement(required = true)
    protected BigDecimal flatFee;
    @XmlElement(required = true)
    protected String effctvFrom;
    @XmlElement(required = true)
    protected String effctvTo;

    /**
     * Gets the value of the tranAmtRangeMax property.
     * 
     */
    public long getTranAmtRangeMax() {
        return tranAmtRangeMax;
    }

    /**
     * Sets the value of the tranAmtRangeMax property.
     * 
     */
    public void setTranAmtRangeMax(long value) {
        this.tranAmtRangeMax = value;
    }

    /**
     * Gets the value of the tranAmtRangeMin property.
     * 
     */
    public long getTranAmtRangeMin() {
        return tranAmtRangeMin;
    }

    /**
     * Sets the value of the tranAmtRangeMin property.
     * 
     */
    public void setTranAmtRangeMin(long value) {
        this.tranAmtRangeMin = value;
    }

    /**
     * Gets the value of the percentFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentFee() {
        return percentFee;
    }

    /**
     * Sets the value of the percentFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentFee(BigDecimal value) {
        this.percentFee = value;
    }

    /**
     * Gets the value of the flatFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFlatFee() {
        return flatFee;
    }

    /**
     * Sets the value of the flatFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFlatFee(BigDecimal value) {
        this.flatFee = value;
    }

    /**
     * Gets the value of the effctvFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvFrom() {
        return effctvFrom;
    }

    /**
     * Sets the value of the effctvFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvFrom(String value) {
        this.effctvFrom = value;
    }

    /**
     * Gets the value of the effctvTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvTo() {
        return effctvTo;
    }

    /**
     * Sets the value of the effctvTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvTo(String value) {
        this.effctvTo = value;
    }

}
