//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterchangeFee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterchangeFee"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="feeCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="feeDesc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="feeDirection" type="{http://bbps.org/schema}InterchangeFeeDirection"/&gt;
 *         &lt;element name="interchangeFeeDetails" type="{http://bbps.org/schema}InterchangeFeeDetailsType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterchangeFee", propOrder = {
    "feeCode",
    "feeDesc",
    "feeDirection",
    "interchangeFeeDetails"
})
public class InterchangeFee
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected String feeCode;
    @XmlElement(required = true)
    protected String feeDesc;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected InterchangeFeeDirection feeDirection;
    @XmlElement(required = true)
    protected List<InterchangeFeeDetailsType> interchangeFeeDetails;

    /**
     * Gets the value of the feeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * Sets the value of the feeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeCode(String value) {
        this.feeCode = value;
    }

    /**
     * Gets the value of the feeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeDesc() {
        return feeDesc;
    }

    /**
     * Sets the value of the feeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeDesc(String value) {
        this.feeDesc = value;
    }

    /**
     * Gets the value of the feeDirection property.
     * 
     * @return
     *     possible object is
     *     {@link InterchangeFeeDirection }
     *     
     */
    public InterchangeFeeDirection getFeeDirection() {
        return feeDirection;
    }

    /**
     * Sets the value of the feeDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterchangeFeeDirection }
     *     
     */
    public void setFeeDirection(InterchangeFeeDirection value) {
        this.feeDirection = value;
    }

    /**
     * Gets the value of the interchangeFeeDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interchangeFeeDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterchangeFeeDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterchangeFeeDetailsType }
     * 
     * 
     */
    public List<InterchangeFeeDetailsType> getInterchangeFeeDetails() {
        if (interchangeFeeDetails == null) {
            interchangeFeeDetails = new ArrayList<InterchangeFeeDetailsType>();
        }
        return this.interchangeFeeDetails;
    }

}
