//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterchangeFeeConf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterchangeFeeConf"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mti" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fees" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="defaultFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="effctvFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="effctvTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterchangeFeeConf", propOrder = {
    "mti",
    "paymentMode",
    "paymentChannel",
    "responseCode",
    "fees",
    "defaultFee",
    "effctvFrom",
    "effctvTo"
})
public class InterchangeFeeConf
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected String mti;
    @XmlElement(required = true)
    protected String paymentMode;
    @XmlElement(required = true)
    protected String paymentChannel;
    @XmlElement(required = true)
    protected String responseCode;
    @XmlElement(required = true)
    protected List<String> fees;
    protected boolean defaultFee;
    protected String effctvFrom;
    protected String effctvTo;

    /**
     * Gets the value of the mti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMti() {
        return mti;
    }

    /**
     * Sets the value of the mti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMti(String value) {
        this.mti = value;
    }

    /**
     * Gets the value of the paymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * Sets the value of the paymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMode(String value) {
        this.paymentMode = value;
    }

    /**
     * Gets the value of the paymentChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentChannel() {
        return paymentChannel;
    }

    /**
     * Sets the value of the paymentChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentChannel(String value) {
        this.paymentChannel = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFees() {
        if (fees == null) {
            fees = new ArrayList<String>();
        }
        return this.fees;
    }

    /**
     * Gets the value of the defaultFee property.
     * 
     */
    public boolean isDefaultFee() {
        return defaultFee;
    }

    /**
     * Sets the value of the defaultFee property.
     * 
     */
    public void setDefaultFee(boolean value) {
        this.defaultFee = value;
    }

    /**
     * Gets the value of the effctvFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvFrom() {
        return effctvFrom;
    }

    /**
     * Sets the value of the effctvFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvFrom(String value) {
        this.effctvFrom = value;
    }

    /**
     * Gets the value of the effctvTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvTo() {
        return effctvTo;
    }

    /**
     * Sets the value of the effctvTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvTo(String value) {
        this.effctvTo = value;
    }

}
