//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationAlertTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="NotificationAlertTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADHOC"/&gt;
 *     &lt;enumeration value="STATIC"/&gt;
 *     &lt;enumeration value="REPETITIVE"/&gt;
 *     &lt;enumeration value="BROADCAST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NotificationAlertTypes")
@XmlEnum
public enum NotificationAlertTypes {

    ADHOC,
    STATIC,
    REPETITIVE,
    BROADCAST;

    public String value() {
        return name();
    }

    public static NotificationAlertTypes fromValue(String v) {
        return valueOf(v);
    }

}
