//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationOrderBy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="NotificationOrderBy"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="notification_type"/&gt;
 *     &lt;enumeration value="user_type"/&gt;
 *     &lt;enumeration value="severity"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NotificationOrderBy")
@XmlEnum
public enum NotificationOrderBy {

    @XmlEnumValue("notification_type")
    NOTIFICATION_TYPE("notification_type"),
    @XmlEnumValue("user_type")
    USER_TYPE("user_type"),
    @XmlEnumValue("severity")
    SEVERITY("severity");
    private final String value;

    NotificationOrderBy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NotificationOrderBy fromValue(String v) {
        for (NotificationOrderBy c: NotificationOrderBy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
