//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationRepetIntervelTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="NotificationRepetIntervelTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Once"/&gt;
 *     &lt;enumeration value="Daily"/&gt;
 *     &lt;enumeration value="AlternateDay"/&gt;
 *     &lt;enumeration value="Weekly"/&gt;
 *     &lt;enumeration value="BiWeekly"/&gt;
 *     &lt;enumeration value="Monthly"/&gt;
 *     &lt;enumeration value="SemiMonthly"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NotificationRepetIntervelTypes")
@XmlEnum
public enum NotificationRepetIntervelTypes {

    @XmlEnumValue("Once")
    ONCE("Once"),
    @XmlEnumValue("Daily")
    DAILY("Daily"),
    @XmlEnumValue("AlternateDay")
    ALTERNATE_DAY("AlternateDay"),
    @XmlEnumValue("Weekly")
    WEEKLY("Weekly"),
    @XmlEnumValue("BiWeekly")
    BI_WEEKLY("BiWeekly"),
    @XmlEnumValue("Monthly")
    MONTHLY("Monthly"),
    @XmlEnumValue("SemiMonthly")
    SEMI_MONTHLY("SemiMonthly");
    private final String value;

    NotificationRepetIntervelTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NotificationRepetIntervelTypes fromValue(String v) {
        for (NotificationRepetIntervelTypes c: NotificationRepetIntervelTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
