//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationTargetGroupTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="NotificationTargetGroupTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BBPOUS"/&gt;
 *     &lt;enumeration value="BBPCU"/&gt;
 *     &lt;enumeration value="CUSTOMERS"/&gt;
 *     &lt;enumeration value="BILLERS"/&gt;
 *     &lt;enumeration value="AGENT_INSTITUTIONS"/&gt;
 *     &lt;enumeration value="AGENTS"/&gt;
 *     &lt;enumeration value="OTHERS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NotificationTargetGroupTypes")
@XmlEnum
public enum NotificationTargetGroupTypes {

    BBPOUS,
    BBPCU,
    CUSTOMERS,
    BILLERS,
    AGENT_INSTITUTIONS,
    AGENTS,
    OTHERS;

    public String value() {
        return name();
    }

    public static NotificationTargetGroupTypes fromValue(String v) {
        return valueOf(v);
    }

}
