//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="senderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="targetGroup" type="{http://bbps.org/schema}NotificationTargetGroupTypes"/&gt;
 *         &lt;element name="targetEmails" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetMobiles" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customParams" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="emailTemplateId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="stakeHolder" type="{http://bbps.org/schema}NotificationStakeHolderTypes"/&gt;
 *         &lt;element name="sourceApp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetEntity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="additionalEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationMessage", propOrder = {
    "senderId",
    "targetGroup",
    "targetEmails",
    "targetMobiles",
    "message",
    "purpose",
    "remarks",
    "name",
    "customParams",
    "emailTemplateId",
    "stakeHolder",
    "sourceApp",
    "targetEntity",
    "additionalEmail"
})
public class NotificationMessage
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String senderId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationTargetGroupTypes targetGroup;
    @XmlElement(required = true)
    protected String targetEmails;
    @XmlElement(required = true)
    protected String targetMobiles;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected String purpose;
    protected String remarks;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String customParams;
    protected int emailTemplateId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationStakeHolderTypes stakeHolder;
    @XmlElement(required = true)
    protected String sourceApp;
    protected String targetEntity;
    protected String additionalEmail;

    /**
     * Gets the value of the senderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderId(String value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the targetGroup property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public NotificationTargetGroupTypes getTargetGroup() {
        return targetGroup;
    }

    /**
     * Sets the value of the targetGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public void setTargetGroup(NotificationTargetGroupTypes value) {
        this.targetGroup = value;
    }

    /**
     * Gets the value of the targetEmails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEmails() {
        return targetEmails;
    }

    /**
     * Sets the value of the targetEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEmails(String value) {
        this.targetEmails = value;
    }

    /**
     * Gets the value of the targetMobiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMobiles() {
        return targetMobiles;
    }

    /**
     * Sets the value of the targetMobiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMobiles(String value) {
        this.targetMobiles = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the customParams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomParams() {
        return customParams;
    }

    /**
     * Sets the value of the customParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomParams(String value) {
        this.customParams = value;
    }

    /**
     * Gets the value of the emailTemplateId property.
     * 
     */
    public int getEmailTemplateId() {
        return emailTemplateId;
    }

    /**
     * Sets the value of the emailTemplateId property.
     * 
     */
    public void setEmailTemplateId(int value) {
        this.emailTemplateId = value;
    }

    /**
     * Gets the value of the stakeHolder property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public NotificationStakeHolderTypes getStakeHolder() {
        return stakeHolder;
    }

    /**
     * Sets the value of the stakeHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public void setStakeHolder(NotificationStakeHolderTypes value) {
        this.stakeHolder = value;
    }

    /**
     * Gets the value of the sourceApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceApp() {
        return sourceApp;
    }

    /**
     * Sets the value of the sourceApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceApp(String value) {
        this.sourceApp = value;
    }

    /**
     * Gets the value of the targetEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntity() {
        return targetEntity;
    }

    /**
     * Sets the value of the targetEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntity(String value) {
        this.targetEntity = value;
    }

    /**
     * Gets the value of the additionalEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalEmail() {
        return additionalEmail;
    }

    /**
     * Sets the value of the additionalEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalEmail(String value) {
        this.additionalEmail = value;
    }

}
