//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlanDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="categoryType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="categorySubType" type="{http://bbps.org/schema}CategorySubType"/&gt;
 *         &lt;element name="amountInRupees" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="planDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="planAdditionalInfo" type="{http://bbps.org/schema}PlanAdditionalInfo" minOccurs="0"/&gt;
 *         &lt;element name="effctvFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="effctvTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="supportRecurringMandate" type="{http://bbps.org/schema}SupportRecurringMandate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlanDetail", propOrder = {
    "id",
    "billerId",
    "categoryType",
    "categorySubType",
    "amountInRupees",
    "planDescription",
    "planAdditionalInfo",
    "effctvFrom",
    "effctvTo",
    "status",
    "supportRecurringMandate"
})
public class PlanDetail
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String billerId;
    @XmlElement(required = true)
    protected String categoryType;
    @XmlElement(required = true)
    protected CategorySubType categorySubType;
    protected double amountInRupees;
    @XmlElement(required = true)
    protected String planDescription;
    protected PlanAdditionalInfo planAdditionalInfo;
    @XmlElement(required = true)
    protected String effctvFrom;
    protected String effctvTo;
    @XmlElement(required = true)
    protected String status;
    @XmlSchemaType(name = "string")
    protected SupportRecurringMandate supportRecurringMandate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the categoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryType() {
        return categoryType;
    }

    /**
     * Sets the value of the categoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryType(String value) {
        this.categoryType = value;
    }

    /**
     * Gets the value of the categorySubType property.
     * 
     * @return
     *     possible object is
     *     {@link CategorySubType }
     *     
     */
    public CategorySubType getCategorySubType() {
        return categorySubType;
    }

    /**
     * Sets the value of the categorySubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategorySubType }
     *     
     */
    public void setCategorySubType(CategorySubType value) {
        this.categorySubType = value;
    }

    /**
     * Gets the value of the amountInRupees property.
     * 
     */
    public double getAmountInRupees() {
        return amountInRupees;
    }

    /**
     * Sets the value of the amountInRupees property.
     * 
     */
    public void setAmountInRupees(double value) {
        this.amountInRupees = value;
    }

    /**
     * Gets the value of the planDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanDescription() {
        return planDescription;
    }

    /**
     * Sets the value of the planDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanDescription(String value) {
        this.planDescription = value;
    }

    /**
     * Gets the value of the planAdditionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PlanAdditionalInfo }
     *     
     */
    public PlanAdditionalInfo getPlanAdditionalInfo() {
        return planAdditionalInfo;
    }

    /**
     * Sets the value of the planAdditionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanAdditionalInfo }
     *     
     */
    public void setPlanAdditionalInfo(PlanAdditionalInfo value) {
        this.planAdditionalInfo = value;
    }

    /**
     * Gets the value of the effctvFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvFrom() {
        return effctvFrom;
    }

    /**
     * Sets the value of the effctvFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvFrom(String value) {
        this.effctvFrom = value;
    }

    /**
     * Gets the value of the effctvTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffctvTo() {
        return effctvTo;
    }

    /**
     * Sets the value of the effctvTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffctvTo(String value) {
        this.effctvTo = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the supportRecurringMandate property.
     * 
     * @return
     *     possible object is
     *     {@link SupportRecurringMandate }
     *     
     */
    public SupportRecurringMandate getSupportRecurringMandate() {
        return supportRecurringMandate;
    }

    /**
     * Sets the value of the supportRecurringMandate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportRecurringMandate }
     *     
     */
    public void setSupportRecurringMandate(SupportRecurringMandate value) {
        this.supportRecurringMandate = value;
    }

}
