//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pmtMtdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pmtMtdType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="quickPay" type="{http://bbps.org/schema}qckPayType" /&gt;
 *       &lt;attribute name="splitPay" type="{http://bbps.org/schema}spltPayType" /&gt;
 *       &lt;attribute name="OFFUSPay" type="{http://bbps.org/schema}offUsPayType" /&gt;
 *       &lt;attribute name="paymentMode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pmtMtdType")
public class PmtMtdType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "quickPay")
    protected QckPayType quickPay;
    @XmlAttribute(name = "splitPay")
    protected SpltPayType splitPay;
    @XmlAttribute(name = "OFFUSPay")
    protected OffUsPayType offusPay;
    @XmlAttribute(name = "paymentMode")
    protected String paymentMode;

    /**
     * Gets the value of the quickPay property.
     * 
     * @return
     *     possible object is
     *     {@link QckPayType }
     *     
     */
    public QckPayType getQuickPay() {
        return quickPay;
    }

    /**
     * Sets the value of the quickPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link QckPayType }
     *     
     */
    public void setQuickPay(QckPayType value) {
        this.quickPay = value;
    }

    /**
     * Gets the value of the splitPay property.
     * 
     * @return
     *     possible object is
     *     {@link SpltPayType }
     *     
     */
    public SpltPayType getSplitPay() {
        return splitPay;
    }

    /**
     * Sets the value of the splitPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpltPayType }
     *     
     */
    public void setSplitPay(SpltPayType value) {
        this.splitPay = value;
    }

    /**
     * Gets the value of the offusPay property.
     * 
     * @return
     *     possible object is
     *     {@link OffUsPayType }
     *     
     */
    public OffUsPayType getOFFUSPay() {
        return offusPay;
    }

    /**
     * Sets the value of the offusPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffUsPayType }
     *     
     */
    public void setOFFUSPay(OffUsPayType value) {
        this.offusPay = value;
    }

    /**
     * Gets the value of the paymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * Sets the value of the paymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMode(String value) {
        this.paymentMode = value;
    }

}
