//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchMyBiller complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchMyBiller"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="mybiller" type="{http://bbps.org/schema}myBiller" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchMyBiller")
public class SearchMyBiller
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "mybiller")
    protected MyBiller mybiller;

    /**
     * Gets the value of the mybiller property.
     * 
     * @return
     *     possible object is
     *     {@link MyBiller }
     *     
     */
    public MyBiller getMybiller() {
        return mybiller;
    }

    /**
     * Sets the value of the mybiller property.
     * 
     * @param value
     *     allowed object is
     *     {@link MyBiller }
     *     
     */
    public void setMybiller(MyBiller value) {
        this.mybiller = value;
    }

}
