//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="creatorId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetUserId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="commChannel" type="{http://bbps.org/schema}NotificationCommChannelTypes" minOccurs="0"/&gt;
 *         &lt;element name="notificationType" type="{http://bbps.org/schema}NotificationTypes" minOccurs="0"/&gt;
 *         &lt;element name="stakeHolder" type="{http://bbps.org/schema}NotificationStakeHolderTypes"/&gt;
 *         &lt;element name="severity" type="{http://bbps.org/schema}NotificationSeverityTypes" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="repetInterval" type="{http://bbps.org/schema}NotificationRepetIntervelTypes" minOccurs="0"/&gt;
 *         &lt;element name="targetGroup" type="{http://bbps.org/schema}NotificationTargetGroupTypes"/&gt;
 *         &lt;element name="dateSearch" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="orderByColumn" type="{http://bbps.org/schema}NotificationOrderBy" minOccurs="0"/&gt;
 *         &lt;element name="orderDirection" type="{http://bbps.org/schema}NotificationOrderDirection" minOccurs="0"/&gt;
 *         &lt;element name="pageNo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creatorId",
    "targetUserId",
    "commChannel",
    "notificationType",
    "stakeHolder",
    "severities",
    "repetInterval",
    "targetGroup",
    "dateSearch",
    "startDate",
    "endDate",
    "orderByColumn",
    "orderDirection",
    "pageNo",
    "pageSize"
})
@XmlRootElement(name = "SearchNotificationRequest")
public class SearchNotificationRequest
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected String creatorId;
    @XmlElement(required = true)
    protected String targetUserId;
    @XmlSchemaType(name = "string")
    protected NotificationCommChannelTypes commChannel;
    @XmlSchemaType(name = "string")
    protected NotificationTypes notificationType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationStakeHolderTypes stakeHolder;
    @XmlElement(name = "severity")
    @XmlSchemaType(name = "string")
    protected List<NotificationSeverityTypes> severities;
    @XmlSchemaType(name = "string")
    protected NotificationRepetIntervelTypes repetInterval;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NotificationTargetGroupTypes targetGroup;
    protected boolean dateSearch;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlSchemaType(name = "string")
    protected NotificationOrderBy orderByColumn;
    @XmlSchemaType(name = "string")
    protected NotificationOrderDirection orderDirection;
    protected Integer pageNo;
    protected Integer pageSize;

    /**
     * Gets the value of the creatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * Sets the value of the creatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorId(String value) {
        this.creatorId = value;
    }

    /**
     * Gets the value of the targetUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * Sets the value of the targetUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUserId(String value) {
        this.targetUserId = value;
    }

    /**
     * Gets the value of the commChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationCommChannelTypes }
     *     
     */
    public NotificationCommChannelTypes getCommChannel() {
        return commChannel;
    }

    /**
     * Sets the value of the commChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationCommChannelTypes }
     *     
     */
    public void setCommChannel(NotificationCommChannelTypes value) {
        this.commChannel = value;
    }

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationTypes }
     *     
     */
    public NotificationTypes getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationTypes }
     *     
     */
    public void setNotificationType(NotificationTypes value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the stakeHolder property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public NotificationStakeHolderTypes getStakeHolder() {
        return stakeHolder;
    }

    /**
     * Sets the value of the stakeHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationStakeHolderTypes }
     *     
     */
    public void setStakeHolder(NotificationStakeHolderTypes value) {
        this.stakeHolder = value;
    }

    /**
     * Gets the value of the severities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the severities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeverities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotificationSeverityTypes }
     * 
     * 
     */
    public List<NotificationSeverityTypes> getSeverities() {
        if (severities == null) {
            severities = new ArrayList<NotificationSeverityTypes>();
        }
        return this.severities;
    }

    /**
     * Gets the value of the repetInterval property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationRepetIntervelTypes }
     *     
     */
    public NotificationRepetIntervelTypes getRepetInterval() {
        return repetInterval;
    }

    /**
     * Sets the value of the repetInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationRepetIntervelTypes }
     *     
     */
    public void setRepetInterval(NotificationRepetIntervelTypes value) {
        this.repetInterval = value;
    }

    /**
     * Gets the value of the targetGroup property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public NotificationTargetGroupTypes getTargetGroup() {
        return targetGroup;
    }

    /**
     * Sets the value of the targetGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationTargetGroupTypes }
     *     
     */
    public void setTargetGroup(NotificationTargetGroupTypes value) {
        this.targetGroup = value;
    }

    /**
     * Gets the value of the dateSearch property.
     * 
     */
    public boolean isDateSearch() {
        return dateSearch;
    }

    /**
     * Sets the value of the dateSearch property.
     * 
     */
    public void setDateSearch(boolean value) {
        this.dateSearch = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the orderByColumn property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationOrderBy }
     *     
     */
    public NotificationOrderBy getOrderByColumn() {
        return orderByColumn;
    }

    /**
     * Sets the value of the orderByColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationOrderBy }
     *     
     */
    public void setOrderByColumn(NotificationOrderBy value) {
        this.orderByColumn = value;
    }

    /**
     * Gets the value of the orderDirection property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationOrderDirection }
     *     
     */
    public NotificationOrderDirection getOrderDirection() {
        return orderDirection;
    }

    /**
     * Sets the value of the orderDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationOrderDirection }
     *     
     */
    public void setOrderDirection(NotificationOrderDirection value) {
        this.orderDirection = value;
    }

    /**
     * Gets the value of the pageNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageNo() {
        return pageNo;
    }

    /**
     * Sets the value of the pageNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageNo(Integer value) {
        this.pageNo = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageSize(Integer value) {
        this.pageSize = value;
    }

}
