//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchByFeature.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="searchByFeature"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Upms"/&gt;
 *     &lt;enumeration value="Clickpay"/&gt;
 *     &lt;enumeration value="Upms,Clickpay"/&gt;
 *     &lt;enumeration value="Clickpay,Upms"/&gt;
 *     &lt;enumeration value="Corporate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "searchByFeature")
@XmlEnum
public enum SearchByFeature {

    @XmlEnumValue("Upms")
    UPMS("Upms"),
    @XmlEnumValue("Clickpay")
    CLICKPAY("Clickpay"),
    @XmlEnumValue("Upms,Clickpay")
    UPMS_CLICKPAY("Upms,Clickpay"),
    @XmlEnumValue("Clickpay,Upms")
    CLICKPAY_UPMS("Clickpay,Upms"),
    @XmlEnumValue("Corporate")
    CORPORATE("Corporate");
    private final String value;

    SearchByFeature(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SearchByFeature fromValue(String v) {
        for (SearchByFeature c: SearchByFeature.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
