//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TicketDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TicketDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ticketId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ticketType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ticketStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ticketInitiatedDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ticketClosureDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ticketEstimatedTat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refundedTxnAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refundedPenaltyAmount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TicketDetails")
public class TicketDetails
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "ticketId")
    protected String ticketId;
    @XmlAttribute(name = "ticketType")
    protected String ticketType;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "ticketStatus")
    protected String ticketStatus;
    @XmlAttribute(name = "ticketInitiatedDate")
    protected String ticketInitiatedDate;
    @XmlAttribute(name = "ticketClosureDate")
    protected String ticketClosureDate;
    @XmlAttribute(name = "ticketEstimatedTat")
    protected String ticketEstimatedTat;
    @XmlAttribute(name = "refundedTxnAmount")
    protected String refundedTxnAmount;
    @XmlAttribute(name = "refundedPenaltyAmount")
    protected String refundedPenaltyAmount;

    /**
     * Gets the value of the ticketId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * Sets the value of the ticketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketId(String value) {
        this.ticketId = value;
    }

    /**
     * Gets the value of the ticketType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * Sets the value of the ticketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketType(String value) {
        this.ticketType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ticketStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketStatus() {
        return ticketStatus;
    }

    /**
     * Sets the value of the ticketStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketStatus(String value) {
        this.ticketStatus = value;
    }

    /**
     * Gets the value of the ticketInitiatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketInitiatedDate() {
        return ticketInitiatedDate;
    }

    /**
     * Sets the value of the ticketInitiatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketInitiatedDate(String value) {
        this.ticketInitiatedDate = value;
    }

    /**
     * Gets the value of the ticketClosureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketClosureDate() {
        return ticketClosureDate;
    }

    /**
     * Sets the value of the ticketClosureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketClosureDate(String value) {
        this.ticketClosureDate = value;
    }

    /**
     * Gets the value of the ticketEstimatedTat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketEstimatedTat() {
        return ticketEstimatedTat;
    }

    /**
     * Sets the value of the ticketEstimatedTat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketEstimatedTat(String value) {
        this.ticketEstimatedTat = value;
    }

    /**
     * Gets the value of the refundedTxnAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundedTxnAmount() {
        return refundedTxnAmount;
    }

    /**
     * Sets the value of the refundedTxnAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundedTxnAmount(String value) {
        this.refundedTxnAmount = value;
    }

    /**
     * Gets the value of the refundedPenaltyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundedPenaltyAmount() {
        return refundedPenaltyAmount;
    }

    /**
     * Sets the value of the refundedPenaltyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundedPenaltyAmount(String value) {
        this.refundedPenaltyAmount = value;
    }

}
