//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="transactionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FORWARD TYPE REQUEST"/&gt;
 *     &lt;enumeration value="REVERSAL TYPE REQUEST"/&gt;
 *     &lt;enumeration value="FORWARD TYPE RESPONSE"/&gt;
 *     &lt;enumeration value="REVERSAL TYPE RESPONSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "transactionType")
@XmlEnum
public enum TransactionType {

    @XmlEnumValue("FORWARD TYPE REQUEST")
    FORWARD_TYPE_REQUEST("FORWARD TYPE REQUEST"),
    @XmlEnumValue("REVERSAL TYPE REQUEST")
    REVERSAL_TYPE_REQUEST("REVERSAL TYPE REQUEST"),
    @XmlEnumValue("FORWARD TYPE RESPONSE")
    FORWARD_TYPE_RESPONSE("FORWARD TYPE RESPONSE"),
    @XmlEnumValue("REVERSAL TYPE RESPONSE")
    REVERSAL_TYPE_RESPONSE("REVERSAL TYPE RESPONSE");
    private final String value;

    TransactionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionType fromValue(String v) {
        for (TransactionType c: TransactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
