//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxnStatusComplainResp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxnStatusComplainResp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TxnList" type="{http://bbps.org/schema}TxnList"/&gt;
 *         &lt;element name="Tickets" type="{http://bbps.org/schema}Tickets" minOccurs="0"/&gt;
 *         &lt;element name="CreditAdjustments" type="{http://bbps.org/schema}CreditAdjustments" minOccurs="0"/&gt;
 *         &lt;element name="ForcePaymentDetails" type="{http://bbps.org/schema}ForcePaymentDetails" minOccurs="0"/&gt;
 *         &lt;element name="CustomerDetails" type="{http://bbps.org/schema}CustomerDetails" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="msgId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="complaintId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="openComplaint" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="reopenComplaint" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="complaintStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="assigned" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="responseReason" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txnReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="disposition" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="billNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxnStatusComplainResp", propOrder = {
    "txnList",
    "tickets",
    "creditAdjustments",
    "forcePaymentDetails",
    "customerDetails"
})
public class TxnStatusComplainResp
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "TxnList", required = true)
    protected TxnList txnList;
    @XmlElement(name = "Tickets")
    protected Tickets tickets;
    @XmlElement(name = "CreditAdjustments")
    protected CreditAdjustments creditAdjustments;
    @XmlElement(name = "ForcePaymentDetails")
    protected ForcePaymentDetails forcePaymentDetails;
    @XmlElement(name = "CustomerDetails")
    protected CustomerDetails customerDetails;
    @XmlAttribute(name = "msgId", required = true)
    protected String msgId;
    @XmlAttribute(name = "complaintId")
    protected String complaintId;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "openComplaint")
    protected String openComplaint;
    @XmlAttribute(name = "reopenComplaint")
    protected String reopenComplaint;
    @XmlAttribute(name = "complaintStatus")
    protected String complaintStatus;
    @XmlAttribute(name = "assigned")
    protected String assigned;
    @XmlAttribute(name = "responseCode")
    protected String responseCode;
    @XmlAttribute(name = "responseReason")
    protected String responseReason;
    @XmlAttribute(name = "remarks")
    protected String remarks;
    @XmlAttribute(name = "txnReferenceId")
    protected String txnReferenceId;
    @XmlAttribute(name = "disposition")
    protected String disposition;
    @XmlAttribute(name = "billNumber")
    protected String billNumber;

    /**
     * Gets the value of the txnList property.
     * 
     * @return
     *     possible object is
     *     {@link TxnList }
     *     
     */
    public TxnList getTxnList() {
        return txnList;
    }

    /**
     * Sets the value of the txnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnList }
     *     
     */
    public void setTxnList(TxnList value) {
        this.txnList = value;
    }

    /**
     * Gets the value of the tickets property.
     * 
     * @return
     *     possible object is
     *     {@link Tickets }
     *     
     */
    public Tickets getTickets() {
        return tickets;
    }

    /**
     * Sets the value of the tickets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tickets }
     *     
     */
    public void setTickets(Tickets value) {
        this.tickets = value;
    }

    /**
     * Gets the value of the creditAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link CreditAdjustments }
     *     
     */
    public CreditAdjustments getCreditAdjustments() {
        return creditAdjustments;
    }

    /**
     * Sets the value of the creditAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditAdjustments }
     *     
     */
    public void setCreditAdjustments(CreditAdjustments value) {
        this.creditAdjustments = value;
    }

    /**
     * Gets the value of the forcePaymentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ForcePaymentDetails }
     *     
     */
    public ForcePaymentDetails getForcePaymentDetails() {
        return forcePaymentDetails;
    }

    /**
     * Sets the value of the forcePaymentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcePaymentDetails }
     *     
     */
    public void setForcePaymentDetails(ForcePaymentDetails value) {
        this.forcePaymentDetails = value;
    }

    /**
     * Gets the value of the customerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetails }
     *     
     */
    public CustomerDetails getCustomerDetails() {
        return customerDetails;
    }

    /**
     * Sets the value of the customerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetails }
     *     
     */
    public void setCustomerDetails(CustomerDetails value) {
        this.customerDetails = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the complaintId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplaintId() {
        return complaintId;
    }

    /**
     * Sets the value of the complaintId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplaintId(String value) {
        this.complaintId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the openComplaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenComplaint() {
        return openComplaint;
    }

    /**
     * Sets the value of the openComplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenComplaint(String value) {
        this.openComplaint = value;
    }

    /**
     * Gets the value of the reopenComplaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReopenComplaint() {
        return reopenComplaint;
    }

    /**
     * Sets the value of the reopenComplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReopenComplaint(String value) {
        this.reopenComplaint = value;
    }

    /**
     * Gets the value of the complaintStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplaintStatus() {
        return complaintStatus;
    }

    /**
     * Sets the value of the complaintStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplaintStatus(String value) {
        this.complaintStatus = value;
    }

    /**
     * Gets the value of the assigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigned() {
        return assigned;
    }

    /**
     * Sets the value of the assigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigned(String value) {
        this.assigned = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseReason() {
        return responseReason;
    }

    /**
     * Sets the value of the responseReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseReason(String value) {
        this.responseReason = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the txnReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnReferenceId() {
        return txnReferenceId;
    }

    /**
     * Sets the value of the txnReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnReferenceId(String value) {
        this.txnReferenceId = value;
    }

    /**
     * Gets the value of the disposition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisposition() {
        return disposition;
    }

    /**
     * Sets the value of the disposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisposition(String value) {
        this.disposition = value;
    }

    /**
     * Gets the value of the billNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillNumber() {
        return billNumber;
    }

    /**
     * Sets the value of the billNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillNumber(String value) {
        this.billNumber = value;
    }

}
