//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxnStatusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxnStatusResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Head" type="{http://bbps.org/schema}headType"/&gt;
 *         &lt;element name="Reason" type="{http://bbps.org/schema}reasonType"/&gt;
 *         &lt;element name="Txn" type="{http://bbps.org/schema}txnType"/&gt;
 *         &lt;element name="BillDetails" type="{http://bbps.org/schema}billDetailsType"/&gt;
 *         &lt;element name="BillerResponse" type="{http://bbps.org/schema}billerResponseType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="BillerPlanResponse" type="{http://bbps.org/schema}billerPlanResponseType" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInfo" type="{http://bbps.org/schema}additionalInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Upms" type="{http://bbps.org/schema}upmsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxnStatusResponse", propOrder = {
    "head",
    "reason",
    "txn",
    "billDetails",
    "billerResponses",
    "billerPlanResponse",
    "additionalInfo",
    "upms"
})
@XmlRootElement(name = "TxnStatusResponse")
public class TxnStatusResponse
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Reason", required = true)
    protected ReasonType reason;
    @XmlElement(name = "Txn", required = true)
    protected TxnType txn;
    @XmlElement(name = "BillDetails", required = true)
    protected BillDetailsType billDetails;
    @XmlElement(name = "BillerResponse", required = true)
    protected List<BillerResponseType> billerResponses;
    @XmlElement(name = "BillerPlanResponse")
    protected BillerPlanResponseType billerPlanResponse;
    @XmlElement(name = "AdditionalInfo")
    protected AdditionalInfoType additionalInfo;
    @XmlElement(name = "Upms")
    protected UpmsType upms;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonType }
     *     
     */
    public ReasonType getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonType }
     *     
     */
    public void setReason(ReasonType value) {
        this.reason = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link TxnType }
     *     
     */
    public TxnType getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnType }
     *     
     */
    public void setTxn(TxnType value) {
        this.txn = value;
    }

    /**
     * Gets the value of the billDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BillDetailsType }
     *     
     */
    public BillDetailsType getBillDetails() {
        return billDetails;
    }

    /**
     * Sets the value of the billDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillDetailsType }
     *     
     */
    public void setBillDetails(BillDetailsType value) {
        this.billDetails = value;
    }

    /**
     * Gets the value of the billerResponses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billerResponses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillerResponses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillerResponseType }
     * 
     * 
     */
    public List<BillerResponseType> getBillerResponses() {
        if (billerResponses == null) {
            billerResponses = new ArrayList<BillerResponseType>();
        }
        return this.billerResponses;
    }

    /**
     * Gets the value of the billerPlanResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BillerPlanResponseType }
     *     
     */
    public BillerPlanResponseType getBillerPlanResponse() {
        return billerPlanResponse;
    }

    /**
     * Sets the value of the billerPlanResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerPlanResponseType }
     *     
     */
    public void setBillerPlanResponse(BillerPlanResponseType value) {
        this.billerPlanResponse = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoType }
     *     
     */
    public AdditionalInfoType getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoType }
     *     
     */
    public void setAdditionalInfo(AdditionalInfoType value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the upms property.
     * 
     * @return
     *     possible object is
     *     {@link UpmsType }
     *     
     */
    public UpmsType getUpms() {
        return upms;
    }

    /**
     * Sets the value of the upms property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpmsType }
     *     
     */
    public void setUpms(UpmsType value) {
        this.upms = value;
    }

}
