//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for txnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="txnType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RiskScores" type="{http://bbps.org/schema}riskScoresType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="msgId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="txnReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="xchangeId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="directBillChannel" type="{http://bbps.org/schema}directBillChannelType" /&gt;
 *       &lt;attribute name="directBillContentId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="paymentRefId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txnType", propOrder = {
    "riskScores"
})
public class TxnType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "RiskScores")
    protected RiskScoresType riskScores;
    @XmlAttribute(name = "ts", required = true)
    protected String ts;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "msgId")
    protected String msgId;
    @XmlAttribute(name = "txnReferenceId")
    protected String txnReferenceId;
    @XmlAttribute(name = "xchangeId")
    protected String xchangeId;
    @XmlAttribute(name = "directBillChannel")
    protected DirectBillChannelType directBillChannel;
    @XmlAttribute(name = "directBillContentId")
    protected String directBillContentId;
    @XmlAttribute(name = "paymentRefId")
    protected String paymentRefId;
    @XmlAttribute(name = "tId")
    protected String tId;

    /**
     * Gets the value of the riskScores property.
     * 
     * @return
     *     possible object is
     *     {@link RiskScoresType }
     *     
     */
    public RiskScoresType getRiskScores() {
        return riskScores;
    }

    /**
     * Sets the value of the riskScores property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskScoresType }
     *     
     */
    public void setRiskScores(RiskScoresType value) {
        this.riskScores = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the txnReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnReferenceId() {
        return txnReferenceId;
    }

    /**
     * Sets the value of the txnReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnReferenceId(String value) {
        this.txnReferenceId = value;
    }

    /**
     * Gets the value of the xchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXchangeId() {
        return xchangeId;
    }

    /**
     * Sets the value of the xchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXchangeId(String value) {
        this.xchangeId = value;
    }

    /**
     * Gets the value of the directBillChannel property.
     * 
     * @return
     *     possible object is
     *     {@link DirectBillChannelType }
     *     
     */
    public DirectBillChannelType getDirectBillChannel() {
        return directBillChannel;
    }

    /**
     * Sets the value of the directBillChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectBillChannelType }
     *     
     */
    public void setDirectBillChannel(DirectBillChannelType value) {
        this.directBillChannel = value;
    }

    /**
     * Gets the value of the directBillContentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectBillContentId() {
        return directBillContentId;
    }

    /**
     * Sets the value of the directBillContentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectBillContentId(String value) {
        this.directBillContentId = value;
    }

    /**
     * Gets the value of the paymentRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentRefId() {
        return paymentRefId;
    }

    /**
     * Sets the value of the paymentRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentRefId(String value) {
        this.paymentRefId = value;
    }

    /**
     * Gets the value of the tId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTId() {
        return tId;
    }

    /**
     * Sets the value of the tId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTId(String value) {
        this.tId = value;
    }

}
