//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.26 at 11:01:11 AM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpmsBillerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="UpmsBillerType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SINGLE"/&gt;
 *     &lt;enumeration value="MULTIPLE"/&gt;
 *     &lt;enumeration value="SPECIAL"/&gt;
 *     &lt;enumeration value="NOT_SUPPORTED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UpmsBillerType")
@XmlEnum
public enum UpmsBillerType {

    SINGLE,
    MULTIPLE,
    SPECIAL,
    NOT_SUPPORTED;

    public String value() {
        return name();
    }

    public static UpmsBillerType fromValue(String v) {
        return valueOf(v);
    }

}
