//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.bbps.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for upmsTxnType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="upmsTxnType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PRESENTMENT_REGISTRATION"/&gt;
 *     &lt;enumeration value="BILL_PRESENTMENT"/&gt;
 *     &lt;enumeration value="BILL_PAYMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "upmsTxnType")
@XmlEnum
public enum UpmsTxnType {

    PRESENTMENT_REGISTRATION,
    BILL_PRESENTMENT,
    BILL_PAYMENT;

    public String value() {
        return name();
    }

    public static UpmsTxnType fromValue(String v) {
        return valueOf(v);
    }

}
