server.port=8115
spring.datasource.url=jdbc:postgresql://localhost:5432/ayushman?currentSchema=billerdb_3
spring.datasource.username=postgres
spring.datasource.password=postgres
ou.id=BBPS003
cu.domain=http://localhost:8112
bbps.ip=http://localhost:8112