server.port=8113
spring.datasource.url=jdbc:postgresql://localhost:5432/ayushman?currentSchema=billerdb_2
spring.datasource.username=postgres
spring.datasource.password=postgres
ou.id=BBPS002
cu.domain=http://localhost:8112
bbps.ip=http://localhost:8112