server.port=8111
spring.datasource.url=jdbc:postgresql://localhost:5432/ayushman?currentSchema=billerdb_1
spring.datasource.username=postgres
spring.datasource.password=postgres
ou.id=BBPS001
cu.domain=http://localhost:8112
bbps.ip=http://localhost:8112