//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.upms.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for billNotify complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="billNotify"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillPaymentNotifications" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Ts" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="BillerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PresentmentRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DateOfPayment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Mandate" type="{http://upms.org/schema}mandateType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "billNotify", propOrder = {
    "billPaymentNotifications"
})
public class BillNotify
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "BillPaymentNotifications", required = true)
    protected List<BillNotify.BillPaymentNotifications> billPaymentNotifications;

    /**
     * Gets the value of the billPaymentNotifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billPaymentNotifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillPaymentNotifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillNotify.BillPaymentNotifications }
     * 
     * 
     */
    public List<BillNotify.BillPaymentNotifications> getBillPaymentNotifications() {
        if (billPaymentNotifications == null) {
            billPaymentNotifications = new ArrayList<BillNotify.BillPaymentNotifications>();
        }
        return this.billPaymentNotifications;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Ts" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="BillerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PresentmentRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DateOfPayment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Mandate" type="{http://upms.org/schema}mandateType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refId",
        "ts",
        "billerId",
        "presentmentRefId",
        "dateOfPayment",
        "mandate"
    })
    public static class BillPaymentNotifications
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(name = "RefId", required = true)
        protected String refId;
        @XmlElement(name = "Ts", required = true)
        protected String ts;
        @XmlElement(name = "BillerId", required = true)
        protected String billerId;
        @XmlElement(name = "PresentmentRefId", required = true)
        protected String presentmentRefId;
        @XmlElement(name = "DateOfPayment", required = true)
        protected String dateOfPayment;
        @XmlElement(name = "Mandate", required = true)
        protected MandateType mandate;

        /**
         * Gets the value of the refId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefId() {
            return refId;
        }

        /**
         * Sets the value of the refId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefId(String value) {
            this.refId = value;
        }

        /**
         * Gets the value of the ts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTs() {
            return ts;
        }

        /**
         * Sets the value of the ts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTs(String value) {
            this.ts = value;
        }

        /**
         * Gets the value of the billerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillerId() {
            return billerId;
        }

        /**
         * Sets the value of the billerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillerId(String value) {
            this.billerId = value;
        }

        /**
         * Gets the value of the presentmentRefId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPresentmentRefId() {
            return presentmentRefId;
        }

        /**
         * Sets the value of the presentmentRefId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPresentmentRefId(String value) {
            this.presentmentRefId = value;
        }

        /**
         * Gets the value of the dateOfPayment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateOfPayment() {
            return dateOfPayment;
        }

        /**
         * Sets the value of the dateOfPayment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateOfPayment(String value) {
            this.dateOfPayment = value;
        }

        /**
         * Gets the value of the mandate property.
         * 
         * @return
         *     possible object is
         *     {@link MandateType }
         *     
         */
        public MandateType getMandate() {
            return mandate;
        }

        /**
         * Sets the value of the mandate property.
         * 
         * @param value
         *     allowed object is
         *     {@link MandateType }
         *     
         */
        public void setMandate(MandateType value) {
            this.mandate = value;
        }

    }

}
