//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.14 at 11:36:19 PM IST 
//


package org.upms.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceTagNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DeviceTagNameType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MOBILE"/&gt;
 *     &lt;enumeration value="GEOCODE"/&gt;
 *     &lt;enumeration value="POSTAL_CODE"/&gt;
 *     &lt;enumeration value="IP"/&gt;
 *     &lt;enumeration value="INITIATING_CHANNEL"/&gt;
 *     &lt;enumeration value="TERMINAL_ID"/&gt;
 *     &lt;enumeration value="IMEI"/&gt;
 *     &lt;enumeration value="IFSC"/&gt;
 *     &lt;enumeration value="MAC"/&gt;
 *     &lt;enumeration value="OS"/&gt;
 *     &lt;enumeration value="APP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DeviceTagNameType")
@XmlEnum
public enum DeviceTagNameType {

    MOBILE,
    GEOCODE,
    POSTAL_CODE,
    IP,
    INITIATING_CHANNEL,
    TERMINAL_ID,
    IMEI,
    IFSC,
    MAC,
    OS,
    APP;

    public String value() {
        return name();
    }

    public static DeviceTagNameType fromValue(String v) {
        return valueOf(v);
    }

}
