//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.upms.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mandateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mandateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RegistrationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DebitInfo" type="{http://upms.org/schema}debitInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Cprn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bprn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MultipleRegistrationExists" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mandateType", propOrder = {
    "registrationType",
    "billPeriod",
    "toDate",
    "debitInfo",
    "cprn",
    "bprn",
    "multipleRegistrationExists",
    "status"
})
public class MandateType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "RegistrationType")
    protected String registrationType;
    @XmlElement(name = "BillPeriod")
    protected String billPeriod;
    @XmlElement(name = "ToDate")
    protected String toDate;
    @XmlElement(name = "DebitInfo")
    protected DebitInfoType debitInfo;
    @XmlElement(name = "Cprn")
    protected String cprn;
    @XmlElement(name = "Bprn")
    protected String bprn;
    @XmlElement(name = "MultipleRegistrationExists")
    protected String multipleRegistrationExists;
    @XmlElement(name = "Status")
    protected String status;

    /**
     * Gets the value of the registrationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationType() {
        return registrationType;
    }

    /**
     * Sets the value of the registrationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationType(String value) {
        this.registrationType = value;
    }

    /**
     * Gets the value of the billPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPeriod() {
        return billPeriod;
    }

    /**
     * Sets the value of the billPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPeriod(String value) {
        this.billPeriod = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(String value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the debitInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DebitInfoType }
     *     
     */
    public DebitInfoType getDebitInfo() {
        return debitInfo;
    }

    /**
     * Sets the value of the debitInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitInfoType }
     *     
     */
    public void setDebitInfo(DebitInfoType value) {
        this.debitInfo = value;
    }

    /**
     * Gets the value of the cprn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCprn() {
        return cprn;
    }

    /**
     * Sets the value of the cprn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCprn(String value) {
        this.cprn = value;
    }

    /**
     * Gets the value of the bprn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBprn() {
        return bprn;
    }

    /**
     * Sets the value of the bprn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBprn(String value) {
        this.bprn = value;
    }

    /**
     * Gets the value of the multipleRegistrationExists property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleRegistrationExists() {
        return multipleRegistrationExists;
    }

    /**
     * Sets the value of the multipleRegistrationExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleRegistrationExists(String value) {
        this.multipleRegistrationExists = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
