//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.upms.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.upms.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.upms.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillNotify }
     * 
     */
    public BillNotify createBillNotify() {
        return new BillNotify();
    }

    /**
     * Create an instance of {@link BillsType }
     * 
     */
    public BillsType createBillsType() {
        return new BillsType();
    }

    /**
     * Create an instance of {@link PaymentsType }
     * 
     */
    public PaymentsType createPaymentsType() {
        return new PaymentsType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link CustomerDtlsType }
     * 
     */
    public CustomerDtlsType createCustomerDtlsType() {
        return new CustomerDtlsType();
    }

    /**
     * Create an instance of {@link MandateType }
     * 
     */
    public MandateType createMandateType() {
        return new MandateType();
    }

    /**
     * Create an instance of {@link DebitInfoType }
     * 
     */
    public DebitInfoType createDebitInfoType() {
        return new DebitInfoType();
    }

    /**
     * Create an instance of {@link BillerParamType }
     * 
     */
    public BillerParamType createBillerParamType() {
        return new BillerParamType();
    }

    /**
     * Create an instance of {@link CustomerParamsType }
     * 
     */
    public CustomerParamsType createCustomerParamsType() {
        return new CustomerParamsType();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link ReasonType }
     * 
     */
    public ReasonType createReasonType() {
        return new ReasonType();
    }

    /**
     * Create an instance of {@link BillerResponseType }
     * 
     */
    public BillerResponseType createBillerResponseType() {
        return new BillerResponseType();
    }

    /**
     * Create an instance of {@link AdditionalInfoType }
     * 
     */
    public AdditionalInfoType createAdditionalInfoType() {
        return new AdditionalInfoType();
    }

    /**
     * Create an instance of {@link AuthType }
     * 
     */
    public AuthType createAuthType() {
        return new AuthType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link PresentmentStatusType }
     * 
     */
    public PresentmentStatusType createPresentmentStatusType() {
        return new PresentmentStatusType();
    }

    /**
     * Create an instance of {@link RecordsType }
     * 
     */
    public RecordsType createRecordsType() {
        return new RecordsType();
    }

    /**
     * Create an instance of {@link BillDetailsType }
     * 
     */
    public BillDetailsType createBillDetailsType() {
        return new BillDetailsType();
    }

    /**
     * Create an instance of {@link BillerType }
     * 
     */
    public BillerType createBillerType() {
        return new BillerType();
    }

    /**
     * Create an instance of {@link BillInfoType }
     * 
     */
    public BillInfoType createBillInfoType() {
        return new BillInfoType();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link Ack }
     * 
     */
    public Ack createAck() {
        return new Ack();
    }

    /**
     * Create an instance of {@link BillNotify.BillPaymentNotifications }
     * 
     */
    public BillNotify.BillPaymentNotifications createBillNotifyBillPaymentNotifications() {
        return new BillNotify.BillPaymentNotifications();
    }

    /**
     * Create an instance of {@link BillsType.BillPresentments }
     * 
     */
    public BillsType.BillPresentments createBillsTypeBillPresentments() {
        return new BillsType.BillPresentments();
    }

    /**
     * Create an instance of {@link PaymentsType.BillPayment }
     * 
     */
    public PaymentsType.BillPayment createPaymentsTypeBillPayment() {
        return new PaymentsType.BillPayment();
    }

}
