//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://upms.org/schema")
package org.upms.schema;
