//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 12:23:58 PM IST 
//


package org.upms.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PresentmentRegRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Cprn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bprn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterType", propOrder = {
    "presentmentRegRefId",
    "cprn",
    "bprn"
})
public class ParameterType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "PresentmentRegRefId")
    protected String presentmentRegRefId;
    @XmlElement(name = "Cprn")
    protected String cprn;
    @XmlElement(name = "Bprn")
    protected String bprn;

    /**
     * Gets the value of the presentmentRegRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentmentRegRefId() {
        return presentmentRegRefId;
    }

    /**
     * Sets the value of the presentmentRegRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentmentRegRefId(String value) {
        this.presentmentRegRefId = value;
    }

    /**
     * Gets the value of the cprn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCprn() {
        return cprn;
    }

    /**
     * Sets the value of the cprn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCprn(String value) {
        this.cprn = value;
    }

    /**
     * Gets the value of the bprn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBprn() {
        return bprn;
    }

    /**
     * Sets the value of the bprn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBprn(String value) {
        this.bprn = value;
    }

}
