//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.upms.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for presentmentStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="presentmentStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PresentmentRegRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RegistrationCreationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BillerId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BillerInitiated" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IssuerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AgentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Customer" type="{http://upms.org/schema}customerDtlsType"/&gt;
 *         &lt;element name="Mandate" type="{http://upms.org/schema}mandateType"/&gt;
 *         &lt;element name="BillerParams" type="{http://upms.org/schema}billerParamType"/&gt;
 *         &lt;element name="CustomerParams" type="{http://upms.org/schema}customerParamsType"/&gt;
 *         &lt;element name="BillerResponse" type="{http://upms.org/schema}billerResponseType" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalInfo" type="{http://upms.org/schema}additionalInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "presentmentStatusType", propOrder = {
    "presentmentRegRefId",
    "registrationCreationDate",
    "billerId",
    "billerInitiated",
    "issuerId",
    "agentId",
    "customer",
    "mandate",
    "billerParams",
    "customerParams",
    "billerResponse",
    "additionalInfo"
})
public class PresentmentStatusType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "PresentmentRegRefId", required = true)
    protected String presentmentRegRefId;
    @XmlElement(name = "RegistrationCreationDate", required = true)
    protected String registrationCreationDate;
    @XmlElement(name = "BillerId", required = true)
    protected String billerId;
    @XmlElement(name = "BillerInitiated", required = true)
    protected String billerInitiated;
    @XmlElement(name = "IssuerId")
    protected String issuerId;
    @XmlElement(name = "AgentId")
    protected String agentId;
    @XmlElement(name = "Customer", required = true)
    protected CustomerDtlsType customer;
    @XmlElement(name = "Mandate", required = true)
    protected MandateType mandate;
    @XmlElement(name = "BillerParams", required = true)
    protected BillerParamType billerParams;
    @XmlElement(name = "CustomerParams", required = true)
    protected CustomerParamsType customerParams;
    @XmlElement(name = "BillerResponse")
    protected BillerResponseType billerResponse;
    @XmlElement(name = "AdditionalInfo")
    protected AdditionalInfoType additionalInfo;

    /**
     * Gets the value of the presentmentRegRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentmentRegRefId() {
        return presentmentRegRefId;
    }

    /**
     * Sets the value of the presentmentRegRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentmentRegRefId(String value) {
        this.presentmentRegRefId = value;
    }

    /**
     * Gets the value of the registrationCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationCreationDate() {
        return registrationCreationDate;
    }

    /**
     * Sets the value of the registrationCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationCreationDate(String value) {
        this.registrationCreationDate = value;
    }

    /**
     * Gets the value of the billerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerId() {
        return billerId;
    }

    /**
     * Sets the value of the billerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerId(String value) {
        this.billerId = value;
    }

    /**
     * Gets the value of the billerInitiated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerInitiated() {
        return billerInitiated;
    }

    /**
     * Sets the value of the billerInitiated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerInitiated(String value) {
        this.billerInitiated = value;
    }

    /**
     * Gets the value of the issuerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * Sets the value of the issuerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerId(String value) {
        this.issuerId = value;
    }

    /**
     * Gets the value of the agentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * Sets the value of the agentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentId(String value) {
        this.agentId = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDtlsType }
     *     
     */
    public CustomerDtlsType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDtlsType }
     *     
     */
    public void setCustomer(CustomerDtlsType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the mandate property.
     * 
     * @return
     *     possible object is
     *     {@link MandateType }
     *     
     */
    public MandateType getMandate() {
        return mandate;
    }

    /**
     * Sets the value of the mandate property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandateType }
     *     
     */
    public void setMandate(MandateType value) {
        this.mandate = value;
    }

    /**
     * Gets the value of the billerParams property.
     * 
     * @return
     *     possible object is
     *     {@link BillerParamType }
     *     
     */
    public BillerParamType getBillerParams() {
        return billerParams;
    }

    /**
     * Sets the value of the billerParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerParamType }
     *     
     */
    public void setBillerParams(BillerParamType value) {
        this.billerParams = value;
    }

    /**
     * Gets the value of the customerParams property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerParamsType }
     *     
     */
    public CustomerParamsType getCustomerParams() {
        return customerParams;
    }

    /**
     * Sets the value of the customerParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerParamsType }
     *     
     */
    public void setCustomerParams(CustomerParamsType value) {
        this.customerParams = value;
    }

    /**
     * Gets the value of the billerResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BillerResponseType }
     *     
     */
    public BillerResponseType getBillerResponse() {
        return billerResponse;
    }

    /**
     * Sets the value of the billerResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillerResponseType }
     *     
     */
    public void setBillerResponse(BillerResponseType value) {
        this.billerResponse = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalInfoType }
     *     
     */
    public AdditionalInfoType getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalInfoType }
     *     
     */
    public void setAdditionalInfo(AdditionalInfoType value) {
        this.additionalInfo = value;
    }

}
