//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.16 at 02:09:01 PM IST 
//


package org.upms.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="remaning" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fetched" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordsType")
public class RecordsType
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlAttribute(name = "limit")
    protected String limit;
    @XmlAttribute(name = "remaning")
    protected String remaning;
    @XmlAttribute(name = "fetched")
    protected String fetched;

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimit(String value) {
        this.limit = value;
    }

    /**
     * Gets the value of the remaning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemaning() {
        return remaning;
    }

    /**
     * Sets the value of the remaning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemaning(String value) {
        this.remaning = value;
    }

    /**
     * Gets the value of the fetched property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetched() {
        return fetched;
    }

    /**
     * Sets the value of the fetched property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetched(String value) {
        this.fetched = value;
    }

}
